package io.github.q93503128.turnbound.world;

import io.github.q93503128.turnbound.combat.BattleOutcome;
import io.github.q93503128.turnbound.combat.CampaignEncounterCatalog;
import io.github.q93503128.turnbound.content.V04Catalogs;
import io.github.q93503128.turnbound.session.BattleSessionManager;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/** Radia hub runtime, Prologue, canonical facilities and all five main-story chapter routes. */
public final class RadiaHubSessionManager {
    private static final List<String> TUTORIALS=List.of("TUTORIAL_1","TUTORIAL_2","TUTORIAL_3");
    private static final Set<String> INTERACTIVE_FACILITIES=Set.of("ECHO_ARCHIVE","FORGE_ANNEX","MARKET_ROW","TRAINING_YARD","RIFT_GATE","MEMORIAL_STEPS","CLOCK_TOWER","BARRACKS");
    private static final Map<UUID,Session> SESSIONS=new LinkedHashMap<>();
    private RadiaHubSessionManager(){}

    public static boolean enter(ServerPlayer player){if(player.level().dimension()!=Level.OVERWORLD)return false;FieldSessionManager.remove(player);GloamwoodSessionManager.remove(player);BrokenAqueductSessionManager.remove(player);EmberQuarrySessionManager.remove(player);OldRelayStationSessionManager.remove(player);remove(player);ServerLevel level=(ServerLevel)player.level();RadiaHubWorld.BuiltHub hub=RadiaHubWorld.build(level);Session session=new Session(hub);SESSIONS.put(player.getUUID(),session);session.refresh(level,player);session.spawn(level);RadiaSafeSpawn.place(level,player);player.sendSystemMessage(Component.literal("TURNBOUND · 라디아").withStyle(ChatFormatting.GOLD));FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.QUEST,null));return true;}
    public static boolean active(ServerPlayer player){return SESSIONS.containsKey(player.getUUID())&&player.level().dimension()==Level.OVERWORLD;}
    public static void refreshProgress(ServerPlayer player){Session session=SESSIONS.get(player.getUUID());if(session==null||!(player.level() instanceof ServerLevel level)||BattleSessionManager.exists(player))return;session.refresh(level,player);FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.QUEST,null));}
    public static void tick(ServerPlayer player){Session session=SESSIONS.get(player.getUUID());if(session==null||BattleSessionManager.exists(player))return;ServerLevel level=(ServerLevel)player.level();if(!RadiaHubWorld.contains(player.position()))RadiaSafeSpawn.place(level,player);if(player.tickCount%20==0)clearMobs(level);}

    public static boolean interactEntity(ServerPlayer player,Entity target){Session session=SESSIONS.get(player.getUUID());if(session==null||target==null)return false;UUID id=target.getUUID();if(id.equals(session.director)){CampaignProgressStore.questInteract(player.getUUID(),"Director Iven");CampaignPersistence.saveIfDirty(player);session.refresh((ServerLevel)player.level(),player);FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.QUEST,null));return true;}if(id.equals(session.relay)){if(session.chapterFourComplete(player)&&!session.relayKeyComplete(player)){int submitted=RelayFragmentBridgeService.submitAvailable(player);if(submitted>0){CampaignPersistence.saveIfDirty(player);player.sendSystemMessage(Component.literal("Relay 조각 제출 "+submitted+"개 · 구 중계소 좌표 복원").withStyle(ChatFormatting.LIGHT_PURPLE));}}FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.TRAVEL,null));return true;}if(id.equals(session.southGate)){if(session.regionUnlocked(player))transitionToMeadow(player);else FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.QUEST,null));return true;}for(int i=0;i<session.tutorialActors.size();i++){if(id.equals(session.tutorialActors.get(i))){session.startTutorial(player,i);return true;}}String facilityId=session.facilityId(id);if(facilityId!=null){session.useFacility(player,facilityId);return true;}return false;}

    public static void command(ServerPlayer player,String raw){Session session=SESSIONS.get(player.getUUID());if(session==null||raw==null||BattleSessionManager.exists(player))return;String[] parts=raw.split("\\|",-1);if(parts.length<2||!"TRAVEL".equals(parts[0]))return;String destination=parts[1];if(("SOUTH_GATE".equals(destination)||AsterMarchRegionCatalog.FT_MEADOW.equals(destination))&&session.regionUnlocked(player)){transitionToMeadow(player);}else if(AsterMarchRegionCatalog.FT_GLOAM.equals(destination)&&session.chapterOneComplete(player)){remove(player);GloamwoodSessionManager.enter(player);}else if(AsterMarchRegionCatalog.FT_AQUEDUCT.equals(destination)&&session.chapterTwoComplete(player)){remove(player);BrokenAqueductSessionManager.enter(player);}else if(AsterMarchRegionCatalog.FT_QUARRY.equals(destination)&&session.chapterThreeComplete(player)){remove(player);EmberQuarrySessionManager.enter(player);}else if(AsterMarchRegionCatalog.FT_RELAY.equals(destination)&&session.relayKeyComplete(player)){remove(player);OldRelayStationSessionManager.enter(player);}else if(AsterMarchRegionCatalog.FT_RADIA.equals(destination)){RadiaSafeSpawn.place((ServerLevel)player.level(),player);FieldNetwork.sync(player,session.snapshot(player,FieldUiSnapshot.Mode.NONE,null));}}
    public static void onBattleEnded(ServerPlayer player,String encounterId,BattleOutcome outcome){Session session=SESSIONS.get(player.getUUID());if(session==null||!TUTORIALS.contains(encounterId))return;session.refresh((ServerLevel)player.level(),player);V04Catalogs.Encounter spec=CampaignEncounterCatalog.spec(encounterId);FieldUiSnapshot.Reward reward=new FieldUiSnapshot.Reward(spec.label(),0,0,outcome==BattleOutcome.ALLY_VICTORY,false);FieldNetwork.sync(player,session.snapshot(player,outcome==BattleOutcome.ALLY_VICTORY?FieldUiSnapshot.Mode.RESULT:FieldUiSnapshot.Mode.QUEST,reward));}
    public static void remove(ServerPlayer player){Session session=SESSIONS.remove(player.getUUID());if(session!=null&&player.level() instanceof ServerLevel level)session.despawn(level);if(session!=null)FieldNetwork.close(player);}
    public static void clearAll(Iterable<ServerPlayer> players){for(ServerPlayer player:players)remove(player);SESSIONS.clear();}
    private static void transitionToMeadow(ServerPlayer player){remove(player);FieldSessionManager.enter(player);ServerLevel level=(ServerLevel)player.level();int y=level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,0,123)+1;player.setPos(0.5,y,123.5);player.setYRot(180.0F);player.setDeltaMovement(Vec3.ZERO);}
    private static void clearMobs(ServerLevel level){AABB area=new AABB(-132,54,-116,132,100,132);for(Mob mob:level.getEntitiesOfClass(Mob.class,area))mob.discard();}

    private static final class Session {
        private final RadiaHubWorld.BuiltHub hub;private UUID director,relay,southGate;private final List<UUID> tutorialActors=new ArrayList<>();private final Map<String,UUID> facilityActors=new LinkedHashMap<>();
        private Session(RadiaHubWorld.BuiltHub hub){this.hub=hub;}
        private void refresh(ServerLevel level,ServerPlayer player){boolean sharedOpen=AsterMarchSharedWorldProgress.regionOpen(level,TurnboundWorldSavedData.REGION_MEADOW);RadiaHubWorld.setSouthGateOpen(level,sharedOpen||regionUnlocked(player));}
        private boolean flag(ServerPlayer player,String flag){return CampaignProgressStore.snapshot(player.getUUID()).quests().unlockFlags().contains(flag);}private boolean complete(ServerPlayer player,String quest){return CampaignProgressStore.snapshot(player.getUUID()).quests().completed().contains(quest);}private boolean cleared(ServerPlayer player,String encounter){return CampaignProgressStore.snapshot(player.getUUID()).clearedEncounters().contains(encounter);}
        private boolean regionUnlocked(ServerPlayer player){return flag(player,"REGION_MEADOW")||complete(player,"MQ_P00_03_south_gate");}private boolean chapterOneComplete(ServerPlayer player){return CampaignContentUnlocks.chapter1Complete(player.getUUID());}private boolean chapterTwoComplete(ServerPlayer player){return CampaignContentUnlocks.chapter2Complete(player.getUUID());}private boolean chapterThreeComplete(ServerPlayer player){return CampaignContentUnlocks.chapter3Complete(player.getUUID());}private boolean chapterFourComplete(ServerPlayer player){return CampaignContentUnlocks.chapter4Complete(player.getUUID());}private boolean relayKeyComplete(ServerPlayer player){return complete(player,"MQ_C05_01_relay_key")||flag(player,"OLD_RELAY_ENTRANCE");}private boolean storyComplete(ServerPlayer player){return CampaignContentUnlocks.storyComplete(player.getUUID());}
        private boolean tutorialUnlocked(ServerPlayer player,int index){if(!flag(player,"BATTLE_TUTORIAL"))return false;Set<String> clears=CampaignProgressStore.snapshot(player.getUUID()).clearedEncounters();return index==0||clears.contains(TUTORIALS.get(index-1));}
        private void startTutorial(ServerPlayer player,int index){if(index<0||index>=TUTORIALS.size()||!tutorialUnlocked(player,index)||cleared(player,TUTORIALS.get(index)))return;Vec3 anchor=hub.tutorialBattleAnchors().get(index);BattleSessionManager.startEncounterAt(player,TUTORIALS.get(index),false,false,anchor,180.0F);}

        private void useFacility(ServerPlayer player,String facilityId){UUID playerId=player.getUUID();switch(facilityId){case"ECHO_ARCHIVE"->{if(!CampaignContentUnlocks.archive(playerId)){locked(player,"Echo Archive · 그라울 클리어 후 소환 기능 해금");return;}MetaNetwork.open(player,"ARCHIVE");}case"FORGE_ANNEX"->{if(!CampaignContentUnlocks.forge(playerId)){locked(player,"Forge Annex · Chapter 1 완료 후 장비 강화 해금");return;}MetaNetwork.open(player,"FORGE");}case"MARKET_ROW"->MetaNetwork.open(player,"MARKET");case"TRAINING_YARD"->{if(!CampaignContentUnlocks.prologueComplete(playerId)){locked(player,"Training Yard · 먼저 Prologue 전투 훈련 3회를 완료해야 합니다.");return;}player.sendSystemMessage(Component.literal("자유 훈련전 · 보상 없음").withStyle(ChatFormatting.YELLOW));BattleSessionManager.start(player);}case"RIFT_GATE"->{if(!CampaignContentUnlocks.endgame(playerId)){locked(player,"Rift Gate · 세라크 격파와 Relay 재연결 후 개방");return;}MetaNetwork.open(player,"RIFT");}case"MEMORIAL_STEPS"->{if(!CampaignContentUnlocks.characterQuestStageOne(playerId)){locked(player,"Memorial Steps · Chapter 2 이후 인연 기록이 개방됩니다.");return;}player.sendSystemMessage(Component.literal("Memorial Steps · 모르웬 및 각성 관련 기록").withStyle(ChatFormatting.LIGHT_PURPLE));MetaNetwork.open(player,"CHARACTERS");}case"CLOCK_TOWER"->{if(!CampaignContentUnlocks.chapter3Complete(playerId)){locked(player,"Clock Tower · 개인 사건은 Chapter 3 완료 이후 조사할 수 있습니다.");return;}player.sendSystemMessage(Component.literal("Clock Tower · 멈춘 시계탑").withStyle(ChatFormatting.AQUA));MetaNetwork.open(player,"CHARACTERS");}case"BARRACKS"->{if(!CampaignContentUnlocks.characterQuestStageOne(playerId)){locked(player,"Barracks · Chapter 2 이후 수비대 기록이 개방됩니다.");return;}player.sendSystemMessage(Component.literal("Barracks · 수비대 관련 기록").withStyle(ChatFormatting.GREEN));MetaNetwork.open(player,"CHARACTERS");}default->{}}}
        private String facilityId(UUID actorId){for(var entry:facilityActors.entrySet())if(entry.getValue().equals(actorId))return entry.getKey();return null;}

        private void spawn(ServerLevel level){
            // The relay hall entrance is on the south wall; Iven stands on the open plaza outside it.
            director=actor(level,new Vec3(0.5,hub.director().y,6.5),"Director Iven",Items.SPYGLASS,ChatFormatting.GOLD);
            // Party composition is entirely managed by E; the redundant physical party-console NPC is intentionally gone.
            relay=actor(level,hub.relay(),"라디아 계전소",Items.AMETHYST_SHARD,ChatFormatting.LIGHT_PURPLE);
            southGate=actor(level,hub.southGate(),"South Gate",Items.IRON_SWORD,ChatFormatting.GREEN);
            for(int i=0;i<TUTORIALS.size();i++)tutorialActors.add(actor(level,hub.tutorialPedestals().get(i),"전투 훈련 "+(i+1),i==2?Items.TNT:Items.IRON_SWORD,ChatFormatting.YELLOW));
            for(RadiaHubWorld.Facility facility:hub.facilities()){if(!INTERACTIVE_FACILITIES.contains(facility.id()))continue;facilityActors.put(facility.id(),actor(level,facility.position(),facilityLabel(facility.id()),facilityItem(facility.id()),facilityColor(facility.id())));}
        }

        private UUID actor(ServerLevel level,Vec3 authored,String name,Item item,ChatFormatting color){Vec3 pos=safeActorPosition(level,authored);ArmorStand stand=new ArmorStand(level,pos.x,pos.y,pos.z);stand.setInvulnerable(true);stand.setNoGravity(true);stand.setShowArms(true);stand.setCustomName(Component.literal(name).withStyle(color));stand.setCustomNameVisible(true);stand.setItemSlot(EquipmentSlot.MAINHAND,item.getDefaultInstance());level.addFreshEntity(stand);return stand.getUUID();}
        private Vec3 safeActorPosition(ServerLevel level,Vec3 authored){BlockPos origin=BlockPos.containing(authored.x,authored.y,authored.z);int[][] offsets={{0,0},{0,1},{1,0},{0,-1},{-1,0},{1,1},{1,-1},{-1,1},{-1,-1},{0,2},{2,0},{0,-2},{-2,0},{0,3},{3,0},{0,-3},{-3,0}};int[] vertical={0,1,-1,2,-2};for(int dy:vertical)for(int[] o:offsets){BlockPos p=origin.offset(o[0],dy,o[1]);var feet=level.getBlockState(p);var head=level.getBlockState(p.above());var floor=level.getBlockState(p.below());if(feet.isAir()&&head.isAir()&&!floor.isAir()&&floor.getFluidState().isEmpty())return Vec3.atBottomCenterOf(p);}return authored;}
        private void despawn(ServerLevel level){desp(level,director);desp(level,relay);desp(level,southGate);for(UUID id:tutorialActors)desp(level,id);tutorialActors.clear();for(UUID id:facilityActors.values())desp(level,id);facilityActors.clear();}
        private void desp(ServerLevel level,UUID id){if(id==null)return;Entity entity=level.getEntity(id);if(entity!=null)entity.discard();}

        private FieldUiSnapshot snapshot(ServerPlayer player,FieldUiSnapshot.Mode mode,FieldUiSnapshot.Reward reward){Set<String> clears=CampaignProgressStore.snapshot(player.getUUID()).clearedEncounters();List<FieldUiSnapshot.Encounter> encounters=new ArrayList<>();int wins=0;for(int i=0;i<TUTORIALS.size();i++){String id=TUTORIALS.get(i);boolean done=clears.contains(id);if(done)wins++;encounters.add(new FieldUiSnapshot.Encounter(id,CampaignEncounterCatalog.spec(id).label(),done,tutorialUnlocked(player,i),false));}List<FieldUiSnapshot.Travel> travels=new ArrayList<>();travels.add(new FieldUiSnapshot.Travel(AsterMarchRegionCatalog.FT_RADIA,"라디아 계전소",true,true));travels.add(new FieldUiSnapshot.Travel("SOUTH_GATE","남문 초원 진입",regionUnlocked(player),false));travels.add(new FieldUiSnapshot.Travel(AsterMarchRegionCatalog.FT_GLOAM,"그늘숲 Chapter 2",chapterOneComplete(player),false));travels.add(new FieldUiSnapshot.Travel(AsterMarchRegionCatalog.FT_AQUEDUCT,"붕괴 수로 Chapter 3",chapterTwoComplete(player),false));travels.add(new FieldUiSnapshot.Travel(AsterMarchRegionCatalog.FT_QUARRY,"잿불 채석장 Chapter 4",chapterThreeComplete(player),false));travels.add(new FieldUiSnapshot.Travel(AsterMarchRegionCatalog.FT_RELAY,"구 중계소 Chapter 5",relayKeyComplete(player),false));return new FieldUiSnapshot(true,mode,wins,3,false,storyComplete(player),0,0,objective(player,wins),dialogue(player),reward==null?FieldUiSnapshot.Reward.none():reward,encounters,List.copyOf(travels));}
        private String objective(ServerPlayer player,int wins){if(!complete(player,"MQ_P00_01_arrival"))return"라디아 도착 · Director Iven과 대화";if(!complete(player,"MQ_P00_02_first_party"))return"첫 파티 · 카이렌 · 변경 사냥꾼 편성 확인";if(!complete(player,"MQ_P00_03_south_gate"))return"남문 개방 · 전투 훈련 "+wins+"/3";if(!chapterOneComplete(player))return"Chapter 1 · 그라울 격파";if(!chapterTwoComplete(player))return"Chapter 2 · 베르나 격파";if(!chapterThreeComplete(player))return"Chapter 3 · ORO-7 정지";if(!chapterFourComplete(player))return"Chapter 4 · 콜바크 격파";if(!relayKeyComplete(player))return"중계소 열쇠 · 라디아 계전소에 세 지역 Relay 조각 제출";if(!storyComplete(player))return"Chapter 5 · 구 중계소에서 세라크와 Relay 재연결 진행";return"메인 스토리 완료 · Rift Gate / Hard / Signature / Awakening 콘텐츠 개방";}
        private String dialogue(ServerPlayer player){if(!complete(player,"MQ_P00_03_south_gate"))return"훈련을 끝내고 남문을 개방해야 한다.";if(!chapterFourComplete(player))return"아스테르 변경의 Relay 이상 신호를 각 지역에서 추적해.";if(!relayKeyComplete(player))return"확보한 세 지역 Relay 조각을 중앙 계전소에 제출하면 구 중계소 좌표를 복원할 수 있다.";if(!storyComplete(player))return"구 중계소 좌표가 복원됐다. 세라크와 마지막 Relay를 확인해.";return"Relay 일부가 재가동되었다. 라디아의 후반 시설과 동쪽 외부 신호가 활성화됐다.";}
        private static void locked(ServerPlayer player,String text){player.sendSystemMessage(Component.literal("TURNBOUND · "+text).withStyle(ChatFormatting.GRAY));}
        private static String facilityLabel(String id){return switch(id){case"ECHO_ARCHIVE"->"Echo Archive · 소환";case"FORGE_ANNEX"->"Forge Annex · 장비 강화";case"MARKET_ROW"->"Market Row · 장비 상점";case"TRAINING_YARD"->"Training Yard · 자유 훈련";case"RIFT_GATE"->"Rift Gate · 균열 관문";case"MEMORIAL_STEPS"->"Memorial Steps · 인연 기록";case"CLOCK_TOWER"->"Clock Tower · 멈춘 시계탑";case"BARRACKS"->"Barracks · 수비대 기록";default->id;};}
        private static Item facilityItem(String id){return switch(id){case"ECHO_ARCHIVE"->Items.BOOK;case"FORGE_ANNEX"->Items.IRON_INGOT;case"MARKET_ROW"->Items.EMERALD;case"TRAINING_YARD"->Items.IRON_SWORD;case"RIFT_GATE"->Items.ENDER_PEARL;case"MEMORIAL_STEPS"->Items.PAPER;case"CLOCK_TOWER"->Items.CLOCK;case"BARRACKS"->Items.SHIELD;default->Items.COMPASS;};}
        private static ChatFormatting facilityColor(String id){return switch(id){case"ECHO_ARCHIVE","RIFT_GATE","MEMORIAL_STEPS"->ChatFormatting.LIGHT_PURPLE;case"FORGE_ANNEX","MARKET_ROW"->ChatFormatting.GOLD;case"TRAINING_YARD","BARRACKS"->ChatFormatting.GREEN;case"CLOCK_TOWER"->ChatFormatting.AQUA;default->ChatFormatting.WHITE;};}
    }
}
