from pathlib import Path
p=Path('projects/living-kingdoms/src/main/java/kr/moonseungjun/livingkingdoms/world/ExternalUrbanFabricBuilder.java')
s=p.read_text()
# Add connectivity helpers if prior diagnostic patch has not landed.
anchor='''    private static String fragmentKey(String resource, FacadeFragment fragment) {'''
if 'private static int fragmentReachableCells(FacadeFragment fragment)' not in s:
    helpers='''    private static Map<Long, BuildingBlock> fragmentBlockMap(FacadeFragment fragment) {\n        Map<Long, BuildingBlock> map = new HashMap<>();\n        for (BuildingBlock block : fragment.blocks) map.put(localKey(block.x, block.y, block.z), block);\n        return map;\n    }\n\n    private static int fragmentReachableCells(FacadeFragment fragment) {\n        Map<Long, BuildingBlock> blocks = fragmentBlockMap(fragment);\n        int doorY = Integer.MAX_VALUE;\n        for (int y = 0; y < fragment.height; y++) {\n            BuildingBlock block = blocks.get(localKey(fragment.entranceX, y, fragment.entranceZ));\n            if (block != null && block.state.getBlock() instanceof DoorBlock) { doorY = y; break; }\n        }\n        if (doorY == Integer.MAX_VALUE) return 0;\n        record Walk(int x, int y, int z) {}\n        java.util.ArrayDeque<Walk> queue = new java.util.ArrayDeque<>();\n        java.util.HashSet<Long> visited = new java.util.HashSet<>();\n        int seedY = sourceWalkableFeetY(blocks, fragment.entranceX, fragment.entranceZ, doorY);\n        if (seedY == Integer.MIN_VALUE) return 0;\n        queue.add(new Walk(fragment.entranceX, seedY, fragment.entranceZ));\n        visited.add(walkKey(fragment.entranceX, seedY, fragment.entranceZ));\n        int[][] dirs = {{1,0},{-1,0},{0,1},{0,-1}};\n        while (!queue.isEmpty()) {\n            Walk current = queue.removeFirst();\n            for (int[] d : dirs) {\n                int nx=current.x()+d[0], nz=current.z()+d[1];\n                if (nx<0 || nx>=fragment.width || nz<0 || nz>=fragment.length) continue;\n                int ny=sourceWalkableFeetY(blocks,nx,nz,current.y());\n                if (ny==Integer.MIN_VALUE || Math.abs(ny-current.y())>1) continue;\n                long key=walkKey(nx,ny,nz);\n                if (visited.add(key)) queue.addLast(new Walk(nx,ny,nz));\n            }\n        }\n        return visited.size();\n    }\n\n    private static long walkKey(int x, int y, int z) {\n        return ((long)(x & 0xffff) << 48) ^ ((long)(y & 0xffff) << 32) ^ (z & 0xffffffffL);\n    }\n\n'''
    if anchor not in s: raise SystemExit('helper anchor missing')
    s=s.replace(anchor,helpers+anchor,1)

old='''        for (BuildingBlock entrance : candidates) {\n            FrontSide side = nearestSide(entrance.x, entrance.z, width, length);\n            if (!usedSides.add(side)) continue;\n            FacadeFragment fragment = cropFragment(\n                    sourceBlocks, entrance, side, width, height, length);\n            if (fragment.blocks.size() >= 500) result.add(fragment);\n        }'''
new='''        for (BuildingBlock entrance : candidates) {\n            CropChoice choice = chooseConnectedCrop(\n                    sourceBlocks, entrance, width, height, length);\n            if (!usedSides.add(choice.side())) continue;\n            FacadeFragment fragment = choice.fragment();\n            if (fragment.blocks.size() >= 500) result.add(fragment);\n        }'''
if old not in s:
    if 'CropChoice choice = chooseConnectedCrop(' not in s: raise SystemExit('createFragments block missing')
else:
    s=s.replace(old,new,1)

insert='''    private static FacadeFragment cropFragment(\n'''
if 'private static CropChoice chooseConnectedCrop(' not in s:
    method='''    private static CropChoice chooseConnectedCrop(\n            List<BuildingBlock> sourceBlocks, BuildingBlock entrance,\n            int width, int height, int length) {\n        FrontSide baselineSide = nearestSide(entrance.x, entrance.z, width, length);\n        FacadeFragment baseline = cropFragment(\n                sourceBlocks, entrance, baselineSide, width, height, length);\n        int baselineReachable = fragmentReachableCells(baseline);\n        if (baselineReachable >= 18) return new CropChoice(baselineSide, baseline, baselineReachable);\n\n        FrontSide bestSide = baselineSide;\n        FacadeFragment best = baseline;\n        int bestReachable = baselineReachable;\n        for (FrontSide candidateSide : FrontSide.values()) {\n            int depth = Math.min(38, candidateSide.horizontal ? width : length);\n            if (edgeDistance(entrance.x, entrance.z, width, length, candidateSide) >= depth) continue;\n            FacadeFragment candidate = cropFragment(\n                    sourceBlocks, entrance, candidateSide, width, height, length);\n            int reachable = fragmentReachableCells(candidate);\n            if (reachable > bestReachable) {\n                bestSide = candidateSide;\n                best = candidate;\n                bestReachable = reachable;\n            }\n        }\n        LivingKingdoms.LOGGER.info(\n                \"LK_ERDEN_CONNECTED_CROP_SELECT entrance={},{} baseline_side={} baseline_reachable={} selected_side={} selected_reachable={} same_footprint=true source_blocks_cut_by_selector=0\",\n                entrance.x, entrance.z, baselineSide, baselineReachable, bestSide, bestReachable);\n        return new CropChoice(bestSide, best, bestReachable);\n    }\n\n    private record CropChoice(FrontSide side, FacadeFragment fragment, int reachable) {}\n\n'''
    if insert not in s: raise SystemExit('crop insert anchor missing')
    s=s.replace(insert,method+insert,1)
p.write_text(s)
