from pathlib import Path

p = Path('projects/living-kingdoms/src/main/java/kr/moonseungjun/livingkingdoms/world/ErdenUrbanFullInteriorPlanCatalog.java')
s = p.read_text(encoding='utf-8')

old = '''                    if (!sourceAir(blocks, x, feetY - 1, z)
                            || !sourceAir(blocks, x, feetY, z)
                            || !sourceAir(blocks, x, feetY + 1, z)) {
'''
new = '''                    if (!sourceAir(snapshot, blocks, x, feetY - 1, z)
                            || !sourceAir(snapshot, blocks, x, feetY, z)
                            || !sourceAir(snapshot, blocks, x, feetY + 1, z)) {
'''
if s.count(old) != 1:
    raise SystemExit(f'candidate sourceAir call block expected once, found {s.count(old)}')
s = s.replace(old, new, 1)

old_method = '''    private static boolean sourceAir(
            Map<Long, ExternalUrbanFabricBuilder.UrbanSourceBlock> blocks,
            int x, int y, int z) {
        ExternalUrbanFabricBuilder.UrbanSourceBlock block = blocks.get(blockKey(x, y, z));
        return block == null || block.state().isAir();
    }
'''
new_method = '''    private static boolean sourceAir(
            ExternalUrbanFabricBuilder.UrbanFragmentSnapshot snapshot,
            Map<Long, ExternalUrbanFabricBuilder.UrbanSourceBlock> blocks,
            int x, int y, int z) {
        ExternalUrbanFabricBuilder.UrbanSourceBlock block = blocks.get(blockKey(x, y, z));
        if (block == null || block.state().isAir()) return true;
        // Crop-face seals are generated by our fragment converter, not authored source structure.
        // Provenance aligns them back to raw schematic AIR and constrains the clearable palette.
        // They may therefore be reserved for stair/floor authoring without violating no-source-cut.
        return ErdenUrbanSyntheticSealProvenance.isClearableSourceAirSeal(
                snapshot.fragmentKey(), x, y, z);
    }
'''
if s.count(old_method) != 1:
    raise SystemExit(f'sourceAir method expected once, found {s.count(old_method)}')
s = s.replace(old_method, new_method, 1)
s = s.replace('public static final int CATALOG_REVISION = 2;',
              'public static final int CATALOG_REVISION = 3;', 1)
p.write_text(s, encoding='utf-8')
print('Patched full interior plan to treat proven synthetic source-air seals as clearable air')
