from pathlib import Path

p=Path('projects/arcane-circle/tools/test_current_source.py')
s=p.read_text(encoding='utf-8')

def once(old,new,label):
    global s
    c=s.count(old)
    if c!=1: raise SystemExit(f'{label}: expected one anchor, got {c}')
    s=s.replace(old,new,1)

once("assert 'mod_version=0.12.1-alpha.46' in gradle\nassert 'VERSION = \"0.12.1-alpha.46\"' in main\nassert '\"version\": \"0.12.1-alpha.46\"' in index",
     "assert 'mod_version=0.12.1-alpha.47' in gradle\nassert 'VERSION = \"0.12.1-alpha.47\"' in main\nassert '\"version\": \"0.12.1-alpha.47\"' in index",'version')
once("'case \"prismatic_wall\" -> 400','case \"control_weather\" -> 600']:",
     "'case \"prismatic_wall\" -> 400','case \"control_weather\" -> 900']:",'visual weather duration')
start=s.index('# Destruction budgets/classification and catastrophe-shaped terrain impact.')
end=s.index('# Sustained Antimagic/Time Stop and Wish preservation.',start)
new='''# Destruction budgets/classification and visible-footprint catastrophe scheduling.\ndestruction=text(magic/'DestructiveMagicService.java')\nfor token in ['getDestroySpeed','getExplosionResistance','destroyBlock','hasChunkAt','MAX_BLOCK_CHANGES_PER_TICK = 720',\n'MAX_BLOCK_SCANS_PER_TICK = 48_000','MAX_DROPPED_BLOCKS_PER_TICK = 96','MAX_PENDING_CELLS_PER_LEVEL = 2_048',\n'MAX_CELLS_PER_TICK = 7','RuptureTask','scheduleFootprint','PENDING','clearAll','TerrainClass','MAJOR','CONDITIONAL',\n'lightning_bolt','thunderwave','gust_of_wind','fissure','travelling continental cut','quakeField','outer faults arrive over subsequent ticks',\n'meteorCrater','visible Meteor Swarm body','annihilationCorridor','deletes a corridor progressively']:\n    assert token in destruction, token\nfor token in ['case "move_earth" -> new Profile(.90, 15.0, 275, false, 9.0, .44, 28.0)',\n              'case "earthquake" -> new Profile(1.00, 21.0, 410, false, 10.5, .56, 56.0)',\n              'case "meteor_swarm" -> new Profile(1.00, 24.0, 220, false, 10.0, .76, 22.0)',\n              'case "world_sunder" -> new Profile(1.00, 33.0, 500, false, 10.5, .90, 24.0)',\n              'case "arcane_annihilation" -> new Profile(1.00, 30.0, 125, false, 7.0, .72, 8.0)']:\n    assert token in destruction, token\nassert 'DestructiveMagicService.quakeField(player, center, r, power)' in text(magic/'HighCircleSpellEffects.java')\nassert 'DestructiveMagicService.meteorCrater(player, impact, radius, power * strike.scale())' in text(magic/'HighCircleSpellEffects.java')\nassert 'DestructiveMagicService.annihilationCorridor(player, start, end, power)' in text(magic/'SpellCastingService.java')\nfusion=text(magic/'FusionSpellEffects.java')\nassert 'DestructiveMagicService.impact(player, "world_sunder", center, radius, power)' in fusion\nassert 'CastTargetSnapshot.targetOr(player, fallback)' in fusion\nassert 'new AABB(lockedPoint, lockedPoint).inflate(2.4)' in fusion\nassert 'targetEntity(player)' not in fusion\n\n'''
s=s[:start]+new+s[end:]
once("'case \"true_polymorph\" -> controlSingle(player, spellId, power, snapshot, 480)','int duration = 600','Math.min(6, targets.size())','state.power() * .24','case \"prismatic_wall\" -> 400','case \"control_weather\" -> 600']:",
     "'case \"true_polymorph\" -> controlSingle(player, spellId, power, snapshot, 480)','int duration = 900','Math.min(3, targets.size())','state.power() * .16','case \"prismatic_wall\" -> 400','case \"control_weather\" -> 900']:",'alpha46 weather upgraded')
append='''\n\n# Alpha.47 catastrophe/time/weather authority pass.\nassert 'DestructiveMagicService.tick(level);' in main\nassert 'DestructiveMagicService.clearAll();' in main\nassert 'visible_footprint_tiled_across_bounded_ticks' in index\nfield=text(magic/'ArcaneFieldService.java')\nfor token in ['FROZEN_ENTITIES','FrozenEntity','entity.setDeltaMovement(Vec3.ZERO)','entity.setNoGravity(true)','raw.setDeltaMovement(frozen.velocity())']:\n    assert token in field, token\nability=root/'src/main/java/kr/moonseungjun/arcanecircle/network/UseArcaneAbilityPayload.java'\nassert ability.exists()\nclient_input=text(client/'ArcaneClient.java')\nfor token in ['ARCANE_ABILITY_KEY','InputConstants.KEY_G','UseArcaneAbilityPayload(0)','event.register(ARCANE_ABILITY_KEY)']:\n    assert token in client_input, token\nnetwork=text(root/'src/main/java/kr/moonseungjun/arcanecircle/network/ArcaneNetwork.java')\nfor token in ['ninefold-arcana-12-1-alpha47','UseArcaneAbilityPayload.TYPE','handleArcaneAbility','SpellGameplayService.useMaintainedAuthority(player)']:\n    assert token in network, token\nfor token in ['useMaintainedAuthority','WEATHER_SPECIAL_READY','WEATHER_BARRAGES','12연속 번개','now + 50L',\n              '/summon minecraft:lightning_bolt','weatherAim','groundStrike','int duration = 900']:\n    assert token in gameplay, token\nmeteor_block=maintenance[maintenance.index('private static void meteorSwarm'):maintenance.index('private static void shapechange')]\nfor token in ['clamp(t / 1.05','sixteen short apertures','if (q >= 1.0) return','port.add(0, -(1.0 + q * 3.2)']:\n    assert token in meteor_block, token\nassert 'double sweep = (t * 1.72)' not in meteor_block\neconomy=text(world/'ArcaneEconomyService.java')\nassert '아르카나' in economy and '에메랄드' not in economy\nassert '아르카나' in grimoire and '에메랄드' not in grimoire\nprint('alpha47_visible_footprint_destruction=PASS')\nprint('alpha47_temporal_motion_stasis=PASS')\nprint('alpha47_weather_active_authority=PASS')\nprint('alpha47_meteor_release_collapse=PASS')\nprint('alpha47_arcana_currency_ui=PASS')\n'''
s+=append
p.write_text(s,encoding='utf-8')
print('alpha47 audit updated')
# trigger-v2
