package kr.moonseungjun.survivalascension;

import com.mojang.logging.LogUtils;
import kr.moonseungjun.survivalascension.apex.ApexHuntSystem;
import kr.moonseungjun.survivalascension.apex.ApexPhaseMutationService;
import kr.moonseungjun.survivalascension.combat.CombatProgression;
import kr.moonseungjun.survivalascension.command.AscensionCommands;
import kr.moonseungjun.survivalascension.compat.ApexContentPackBridge;
import kr.moonseungjun.survivalascension.compat.ApexContentRewardService;
import kr.moonseungjun.survivalascension.compat.ContentPackCompatibility;
import kr.moonseungjun.survivalascension.compat.ContentPackLootBridge;
import kr.moonseungjun.survivalascension.compat.TbsJournalRestorationService;
import kr.moonseungjun.survivalascension.construction.ConstructionProgression;
import kr.moonseungjun.survivalascension.elite.EliteMobSystem;
import kr.moonseungjun.survivalascension.elite.EndgameMutationSystem;
import kr.moonseungjun.survivalascension.elite.WarbandDirector;
import kr.moonseungjun.survivalascension.endgame.AscensionTrialSystem;
import kr.moonseungjun.survivalascension.endgame.FinalAscensionBossSystem;
import kr.moonseungjun.survivalascension.endgame.FinalAscensionSystem;
import kr.moonseungjun.survivalascension.equipment.AscensionAffixes;
import kr.moonseungjun.survivalascension.expedition.ExpeditionIncidentSystem;
import kr.moonseungjun.survivalascension.expedition.ExpeditionInterdictionService;
import kr.moonseungjun.survivalascension.expedition.ExpeditionOperationSystem;
import kr.moonseungjun.survivalascension.expedition.ExpeditionProgression;
import kr.moonseungjun.survivalascension.harvesting.HarvestingProgression;
import kr.moonseungjun.survivalascension.harvesting.IrrigationReplantService;
import kr.moonseungjun.survivalascension.mining.BoreMiningService;
import kr.moonseungjun.survivalascension.mining.MiningProgression;
import kr.moonseungjun.survivalascension.mobility.MobilityProgression;
import kr.moonseungjun.survivalascension.network.SkillNetwork;
import kr.moonseungjun.survivalascension.production.FieldRecoveryService;
import kr.moonseungjun.survivalascension.production.OutpostService;
import kr.moonseungjun.survivalascension.production.OutpostSiegeBreachService;
import kr.moonseungjun.survivalascension.production.OutpostSiegeSystem;
import kr.moonseungjun.survivalascension.woodcutting.WoodcuttingProgression;
import kr.moonseungjun.survivalascension.world.WorldAscensionProgression;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import org.slf4j.Logger;

@Mod(SurvivalAscension.MOD_ID)
public final class SurvivalAscension {
    public static final String MOD_ID = "survivalascension";
    public static final String VERSION = "0.61.0-alpha.1";
    // 0.61 closure pass: acts 1-3 now lead into a Survival-owned three-phase final boss.
    // Completion is stored once at world scope and unlocks bounded Lv100 mobility/construction
    // authority without changing the existing canonical gate or network protocol.
    public static final Logger LOGGER = LogUtils.getLogger();

    public SurvivalAscension(IEventBus modEventBus) {
        modEventBus.addListener(SkillNetwork::onRegisterPayloads);
        NeoForge.EVENT_BUS.addListener(MiningProgression::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(MiningProgression::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(FieldRecoveryService::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(MiningProgression::onBreakSpeed);
        NeoForge.EVENT_BUS.addListener(MiningProgression::onBlockBreak);
        NeoForge.EVENT_BUS.addListener(BoreMiningService::onServerTick);
        NeoForge.EVENT_BUS.addListener(WoodcuttingProgression::onBlockBreak);
        NeoForge.EVENT_BUS.addListener(WoodcuttingProgression::onServerTick);
        NeoForge.EVENT_BUS.addListener(HarvestingProgression::onBreakSpeed);
        NeoForge.EVENT_BUS.addListener(HarvestingProgression::onBlockBreak);
        NeoForge.EVENT_BUS.addListener(HarvestingProgression::onServerTick);
        NeoForge.EVENT_BUS.addListener(IrrigationReplantService::onServerTick);
        NeoForge.EVENT_BUS.addListener(CombatProgression::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(CombatProgression::onIncomingDamage);
        NeoForge.EVENT_BUS.addListener(ApexPhaseMutationService::onIncomingDamage);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onIncomingDamage);
        NeoForge.EVENT_BUS.addListener(CombatProgression::onShieldBlock);
        NeoForge.EVENT_BUS.addListener(CombatProgression::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(FieldRecoveryService::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(ExpeditionOperationSystem::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(OutpostSiegeSystem::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(ApexContentRewardService::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(ConstructionProgression::onBlockPlaced);
        NeoForge.EVENT_BUS.addListener(ConstructionProgression::onServerTick);
        NeoForge.EVENT_BUS.addListener(MobilityProgression::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(MobilityProgression::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(ExpeditionProgression::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(ExpeditionProgression::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(ExpeditionProgression::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(ContentPackCompatibility::onServerStarted);
        NeoForge.EVENT_BUS.addListener(ApexContentPackBridge::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TbsJournalRestorationService::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(TbsJournalRestorationService::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(TbsJournalRestorationService::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(ExpeditionIncidentSystem::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(ExpeditionIncidentSystem::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(ExpeditionOperationSystem::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(ExpeditionInterdictionService::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(ExpeditionOperationSystem::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(ApexHuntSystem::onServerTick);
        NeoForge.EVENT_BUS.addListener(ApexHuntSystem::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(ApexHuntSystem::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(OutpostSiegeSystem::onServerTick);
        NeoForge.EVENT_BUS.addListener(OutpostSiegeBreachService::onServerTick);
        NeoForge.EVENT_BUS.addListener(OutpostSiegeSystem::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(OutpostSiegeSystem::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(OutpostService::onFinalizeSpawn);
        NeoForge.EVENT_BUS.addListener(EliteMobSystem::onFinalizeSpawn);
        NeoForge.EVENT_BUS.addListener(EliteMobSystem::onDamagePre);
        NeoForge.EVENT_BUS.addListener(EliteMobSystem::onDamagePost);
        NeoForge.EVENT_BUS.addListener(EliteMobSystem::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(EndgameMutationSystem::onFinalizeSpawn);
        NeoForge.EVENT_BUS.addListener(EndgameMutationSystem::onDamagePost);
        NeoForge.EVENT_BUS.addListener(EndgameMutationSystem::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(WarbandDirector::onFinalizeSpawn);
        NeoForge.EVENT_BUS.addListener(WarbandDirector::onServerTick);
        NeoForge.EVENT_BUS.addListener(WarbandDirector::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(AscensionTrialSystem::onServerTick);
        NeoForge.EVENT_BUS.addListener(AscensionTrialSystem::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(FinalAscensionSystem::onServerTick);
        NeoForge.EVENT_BUS.addListener(FinalAscensionSystem::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(FinalAscensionSystem::onServerStopping);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onServerTick);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onEntityJoin);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(FinalAscensionBossSystem::onServerStopping);
        NeoForge.EVENT_BUS.addListener(WorldAscensionProgression::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(AscensionAffixes::onEliteDeath);
        NeoForge.EVENT_BUS.addListener(ContentPackLootBridge::onEliteDeath);
        NeoForge.EVENT_BUS.addListener(AscensionCommands::onRegisterCommands);
        LOGGER.info("Survival Ascension {} loaded: three-phase Final Ascension boundary boss + permanent world closure + final Lv100 mobility/construction authority + orderly server-stop encounter cleanup + bounded Final Ascension acts 1-3 + canonical readiness gate + repeatable Ascension Trial + two-stage archetype-specific Apex mutation phases + contested expedition operation interdiction waves + region-targeted Apex Resonance trophies + regional integrated-terrain incidents + bounded general content encounters + targeted Deep resonance recovery + directional Combat Academy fracture lane + data-driven Apex content escorts + runtime content census + high-rank content-pack gear drops + rare bounded field incidents + visible incident perimeters + multiplayer incident admission + selectable server-authoritative construction length + one-time TBS journal restoration + pre-test chunk/accounting hardening + scaled mastery + ranged shooter attribution + spear momentum drive lines + mace outer impact rings + shield guard waves + ranged projectile snapshots/impact bursts + armor affix progression + regional 3/6/9 logistics + frontline freight/local supply + tagged major targets + shovel earthworks + optional expedition biome tags + content-pack gear imprint + physical logistics/freight + civil works + destructible bastion defense", VERSION);
    }
}
