package io.github.q93503128.turnbound.combat;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Deque;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

public final class BattleEngine {
    public static final long TURN_THRESHOLD=1000L; public static final int MAX_REACTION_DEPTH=3;
    private final BattleState state; private final Deque<Reaction> reactions=new ArrayDeque<>(); private final Set<String> emergencyHealingInProgress=new HashSet<>();
    public BattleEngine(BattleState state){this.state=Objects.requireNonNull(state);} public BattleState state(){return state;}
    public CombatantState nextReady(){if(state.outcome()!=BattleOutcome.RUNNING)throw new IllegalStateException("Battle is over");if(state.currentActorId()!=null)return state.combatant(state.currentActorId());List<CombatantState> living=state.combatants().stream().filter(c->!c.downed()).toList();long pulses=living.stream().mapToLong(this::pulsesUntilReady).min().orElseThrow();if(pulses>0){for(var c:living)c.addGauge(pulses*c.speed());state.addLogicalPulse(pulses);}CombatantState ready=living.stream().filter(c->c.gauge()>=TURN_THRESHOLD).max(Comparator.comparingLong(CombatantState::gauge).thenComparingInt(CombatantState::speed).thenComparingInt(c->-c.initiativeSeed())).orElseThrow();state.setCurrentActorId(ready.instanceId());state.addEvent(new BattleEvent("TURN_READY",ready.instanceId(),ready.instanceId(),(int)Math.min(Integer.MAX_VALUE,ready.gauge()),"pulse="+state.logicalPulse()));return ready;}
    private long pulsesUntilReady(CombatantState c){if(c.gauge()>=TURN_THRESHOLD)return 0;long m=TURN_THRESHOLD-c.gauge();return(m+c.speed()-1L)/c.speed();}
    public void useSkill(String actorId,String skillId,String... requestedTargetIds){if(!actorId.equals(state.currentActorId()))throw new IllegalStateException("Not current actor: "+actorId);CombatantState actor=state.combatant(actorId);SkillDefinition skill=actor.definition().skill(skillId);if(actor.downed()||actor.cooldown(skillId)>0)throw new IllegalStateException("Actor unavailable or skill on cooldown");List<CombatantState> targets=resolveTargets(actor,skill,requestedTargetIds);if(skill.id().equals("p02_time_leap")&&targets.getFirst()==actor)throw new IllegalArgumentException("P02 time leap cannot target self");state.addEvent(new BattleEvent("ACTION",actorId,String.join(",",targets.stream().map(CombatantState::instanceId).toList()),0,skillId));boolean direct=skill.effects().stream().anyMatch(e->e.type()==EffectType.DAMAGE);int focus=actor.definition().id().equals("P01")?actor.counter("focus"):0;for(var effect:skill.effects()){applyEffect(actor,skill,targets,effect,focus,0,direct);resolveReactions();}postRules(actor,skill,targets,direct);resolveReactions();if(skill.cooldown()>0)actor.setCooldown(skill.id(),skill.cooldown());actor.spendTurnGauge();tickCooldowns(actor,skill.id());actor.tickStatusesOnOwnTurn();triggerLumeaPassive(actor);state.setCurrentActorId(null);state.addEvent(new BattleEvent("TURN_END",actorId,actorId,0,skillId));}
    private List<CombatantState> resolveTargets(CombatantState actor,SkillDefinition skill,String[] ids){return switch(skill.targetRule()){case SELF->List.of(actor);case ALLY_ALL->state.living(actor.side());case ENEMY_ALL->state.living(actor.side().opposite());case ALLY_SINGLE->List.of(single(ids,actor.side(),false));case ENEMY_SINGLE->List.of(single(ids,actor.side().opposite(),false));case DEAD_ALLY_SINGLE->List.of(single(ids,actor.side(),true));};}
    private CombatantState single(String[] ids,CombatantSide side,boolean down){if(ids.length!=1)throw new IllegalArgumentException("Exactly one target required");CombatantState t=state.combatant(ids[0]);if(t.side()!=side||t.downed()!=down)throw new IllegalArgumentException("Invalid target");return t;}
    private void applyEffect(CombatantState actor,SkillDefinition skill,List<CombatantState> targets,SkillEffect effect,int focus,int depth,boolean direct){switch(effect.type()){case DAMAGE->{for(var target:targets){double p=effect.magnitude();if(actor.definition().id().equals("P01")){p*=1+0.15*focus;if(skill.id().equals("p01_shatter"))p*=1+0.10*focus;}damage(actor,target,p,depth,direct);}}case HEAL->{for(var target:targets){double p=effect.magnitude();if(actor.definition().id().equals("P04")&&skill.id().equals("p04_rest_light")&&target==actor)p=0.70;int v=target.heal((int)Math.floor(actor.attack()*p));state.addEvent(new BattleEvent("HEAL",actor.instanceId(),target.instanceId(),v,skill.id()));}}case BARRIER_MAX_HP->{for(var target:targets){int v=target.addBarrier((int)Math.floor(target.maxHp()*effect.magnitude()));state.addEvent(new BattleEvent("BARRIER",actor.instanceId(),target.instanceId(),v,skill.id()));}}case GAUGE_ADD->{for(var target:targets){long before=target.gauge();target.addGauge(effect.flatValue());state.addEvent(new BattleEvent("GAUGE",actor.instanceId(),target.instanceId(),(int)(target.gauge()-before),skill.id()));}}case SELF_GAUGE_ADD->{long before=actor.gauge();actor.addGauge(effect.flatValue());state.addEvent(new BattleEvent("GAUGE",actor.instanceId(),actor.instanceId(),(int)(actor.gauge()-before),skill.id()));}case GAUGE_AT_LEAST->{for(var target:targets){long before=target.gauge();target.setGauge(Math.max(target.gauge(),effect.flatValue()));state.addEvent(new BattleEvent("GAUGE",actor.instanceId(),target.instanceId(),(int)(target.gauge()-before),skill.id()));}}case GUARD_REDIRECT->{var target=targets.getFirst();if(target==actor)throw new IllegalArgumentException("Guard requires another ally");target.putStatus(new StatusInstance("guard_redirect",actor.instanceId(),effect.duration(),effect.magnitude()));state.addEvent(new BattleEvent("STATUS",actor.instanceId(),target.instanceId(),effect.duration(),"guard_redirect"));}case REVIVE->{var target=targets.getFirst();int hp=target.revive(effect.magnitude());state.addEvent(new BattleEvent("REVIVE",actor.instanceId(),target.instanceId(),hp,skill.id()));}}}
    private void damage(CombatantState actor,CombatantState target,double potency,int depth,boolean direct){if(target.downed())return;int raw=calculateDamage(actor.attack(),target.defense(),potency);var guard=target.status("guard_redirect");if(guard!=null&&direct){var guardian=state.combatant(guard.sourceId());if(!guardian.downed()){int redirected=(int)Math.floor(raw*guard.magnitude());raw-=redirected;int dealt=guardian.takeDamage(redirected);state.addEvent(new BattleEvent("DAMAGE_REDIRECT",actor.instanceId(),guardian.instanceId(),dealt,target.instanceId()));afterDamage(actor,guardian,dealt,depth,direct);}}int dealt=target.takeDamage(raw);state.addEvent(new BattleEvent("DAMAGE",actor.instanceId(),target.instanceId(),dealt,"potency="+potency));afterDamage(actor,target,dealt,depth,direct);}
    private void afterDamage(CombatantState attacker,CombatantState target,int dealt,int depth,boolean direct){if(dealt<=0)return;if(target.downed())state.addEvent(new BattleEvent("DOWN",attacker.instanceId(),target.instanceId(),0,"hp=0"));if(direct&&depth==0&&target.definition().id().equals("P03")&&!target.downed())reactions.addLast(new Reaction(target.instanceId(),attacker.instanceId(),0.65,"P03_COUNTER",1));triggerElysia(target);}
    private void triggerElysia(CombatantState hurt){if(hurt.downed()||hurt.hp()*100>hurt.maxHp()*30)return;for(var e:state.living(hurt.side())){if(!e.definition().id().equals("P04"))continue;String flag="p04_emergency:"+hurt.instanceId();if(e.flag(flag)||!emergencyHealingInProgress.add(hurt.instanceId()))continue;e.setFlag(flag);int healed=hurt.heal((int)Math.floor(e.attack()*0.80));state.addEvent(new BattleEvent("REACTION_HEAL",e.instanceId(),hurt.instanceId(),healed,"P04_LAST_TOUCH"));emergencyHealingInProgress.remove(hurt.instanceId());}}
    private void resolveReactions(){while(!reactions.isEmpty()){Reaction r=reactions.removeFirst();if(r.depth()>MAX_REACTION_DEPTH)continue;var s=state.combatant(r.sourceId());var t=state.combatant(r.targetId());if(s.downed()||t.downed())continue;int dealt=t.takeDamage(calculateDamage(s.attack(),t.defense(),r.potency()));state.addEvent(new BattleEvent("REACTION_DAMAGE",s.instanceId(),t.instanceId(),dealt,r.type()));afterDamage(s,t,dealt,r.depth(),false);}}
    private void postRules(CombatantState actor,SkillDefinition skill,List<CombatantState> targets,boolean direct){if(!actor.definition().id().equals("P01"))return;if(skill.id().equals("p01_duel_lock")){var target=targets.getFirst();if(!target.instanceId().equals(actor.ref("focusTarget"))){actor.setRef("focusTarget",target.instanceId());actor.setCounter("focus",0);}actor.incrementCounter("focus",1,3);}else if(direct&&targets.size()==1){var target=targets.getFirst();String current=actor.ref("focusTarget");if(target.instanceId().equals(current))actor.incrementCounter("focus",1,3);else{actor.setRef("focusTarget",target.instanceId());actor.setCounter("focus",0);}if(target.downed()){actor.setRef("focusTarget",null);actor.setCounter("focus",0);}}}
    private void triggerLumeaPassive(CombatantState actor){for(var lumea:state.living(actor.side()))if(lumea!=actor&&lumea.definition().id().equals("P02")&&actor.speed()<lumea.speed()){lumea.addGauge(60);state.addEvent(new BattleEvent("PASSIVE_GAUGE",lumea.instanceId(),lumea.instanceId(),60,"P02_WAIT_FOR_SLOW"));}}
    private void tickCooldowns(CombatantState actor,String used){for(String id:new ArrayList<>(actor.cooldownsView().keySet()))if(!id.equals(used))actor.setCooldown(id,actor.cooldown(id)-1);}
    public static int calculateDamage(int attack,int defense,double potency){double r=defense/(double)(defense+4L*Math.max(1,attack));r=Math.min(0.65,Math.max(0,r));return Math.max(1,(int)Math.floor(attack*potency*(1-r)));}
    private record Reaction(String sourceId,String targetId,double potency,String type,int depth){}
}
