package io.github.q93503128.turnbound.combat;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public final class P0Scenario {
    private P0Scenario() {}
    public static BattleState create(){List<CombatantState> u=new ArrayList<>();u.add(new CombatantState("ally_kyren",PrototypeRoster.kyren(),CombatantSide.ALLY,0));u.add(new CombatantState("ally_lumea",PrototypeRoster.lumea(),CombatantSide.ALLY,1));u.add(new CombatantState("ally_bram",PrototypeRoster.bram(),CombatantSide.ALLY,2));u.add(new CombatantState("ally_elysia",PrototypeRoster.elysia(),CombatantSide.ALLY,3));u.add(new CombatantState("enemy_a",PrototypeRoster.trainingEnemy("E_TEST_A","훈련 검병",700,95,70,90),CombatantSide.ENEMY,4));u.add(new CombatantState("enemy_b",PrototypeRoster.trainingEnemy("E_TEST_B","훈련 궁수",560,105,55,105),CombatantSide.ENEMY,5));u.add(new CombatantState("enemy_c",PrototypeRoster.trainingEnemy("E_TEST_C","훈련 방패병",950,75,125,70),CombatantSide.ENEMY,6));return new BattleState(u);}
    public static String runAutoDiagnostic(int maxActions){BattleState state=create();BattleEngine engine=new BattleEngine(state);int actions=0;while(state.outcome()==BattleOutcome.RUNNING&&actions<maxActions){CombatantState actor=engine.nextReady();choose(engine,state,actor);actions++;}String timeline=state.events().stream().filter(e->e.type().equals("TURN_READY")).limit(12).map(BattleEvent::sourceId).reduce((a,b)->a+" > "+b).orElse("none");return "outcome="+state.outcome()+", actions="+actions+", pulses="+state.logicalPulse()+", timeline="+timeline;}
    private static void choose(BattleEngine engine,BattleState state,CombatantState actor){if(actor.side()==CombatantSide.ENEMY){engine.useSkill(actor.instanceId(),actor.definition().basicSkillId(),state.living(CombatantSide.ALLY).getFirst().instanceId());return;}switch(actor.definition().id()){case "P01"->{var t=state.living(CombatantSide.ENEMY).getFirst();String s=actor.cooldown("p01_shatter")==0&&actor.counter("focus")>=1?"p01_shatter":"p01_basic";engine.useSkill(actor.instanceId(),s,t.instanceId());}case "P02"->{var t=state.living(CombatantSide.ALLY).stream().filter(c->!c.definition().id().equals("P02")).min(Comparator.comparingLong(CombatantState::gauge)).orElseThrow();engine.useSkill(actor.instanceId(),"p02_basic",t.instanceId());}case "P03"->engine.useSkill(actor.instanceId(),"p03_basic");case "P04"->{if(!state.downed(CombatantSide.ALLY).isEmpty()&&actor.cooldown("p04_revive")==0)engine.useSkill(actor.instanceId(),"p04_revive",state.downed(CombatantSide.ALLY).getFirst().instanceId());else{var t=state.living(CombatantSide.ALLY).stream().min(Comparator.comparingDouble(c->c.hp()/(double)c.maxHp())).orElseThrow();engine.useSkill(actor.instanceId(),"p04_basic",t.instanceId());}}default->throw new IllegalStateException();}}
}
