package kr.moonseungjun.arcanecircle.client;

import kr.moonseungjun.arcanecircle.magic.SixthCircleSpellService;
import kr.moonseungjun.arcanecircle.magic.SpellDefinition;
import net.minecraft.world.phys.Vec3;

import java.util.Set;

/**
 * Alpha.69 gameplay-footprint overlay for redesigned sixth-circle authority.
 *
 * This is not a generic high-circle array. It only exposes authoritative gameplay geometry that
 * must remain readable for the four Value Pass I spells: the actual Mass Suggestion command area,
 * Move Earth trench/berms, Sunbeam corridor width, and Freezing Sphere denial radius.
 */
final class SixthCircleAuthorityOverlay {
    private static final Set<String> AUTHORITY = Set.of(
            "mass_suggestion", "move_earth", "sunbeam", "freezing_sphere");

    private SixthCircleAuthorityOverlay() {}

    static ArcaneWorldMesh release(SpellDefinition spell, Vec3 direction, Vec3 target,
                                   double range, double elapsedSeconds, double durationSeconds) {
        ArcaneWorldMesh.Builder m = ArcaneWorldMesh.detailBuilder(720);
        if (spell == null || spell.circle() != 6 || !AUTHORITY.contains(spell.id())) return m.build();
        double t = Math.max(0.0, elapsedSeconds);
        switch (spell.id()) {
            case "mass_suggestion" -> massSuggestion(m, target, range, t, durationSeconds);
            case "move_earth" -> moveEarth(m, direction, target, range, t);
            case "sunbeam" -> sunbeam(m, direction, target, t, durationSeconds);
            case "freezing_sphere" -> freezingSphere(m, target, range, t, durationSeconds);
            default -> { }
        }
        return m.build();
    }

    /** Actual behavioral-command radius; arrows point outward because the order is battlefield exit. */
    private static void massSuggestion(ArcaneWorldMesh.Builder m, Vec3 target, double range,
                                       double t, double durationSeconds) {
        ArcaneWorldMesh.Basis g = ArcaneWorldMesh.Basis.ground();
        double radius = SixthCircleSpellService.massSuggestionRadius(range);
        double life = clamp(t / Math.max(.05, durationSeconds), 0.0, 1.0);
        double breathe = .97 + .03 * Math.sin(t * 1.7);
        m.circle(g, target, radius * breathe, 82, .72F);
        m.circle(g, target, radius * .62, 58, .30F);
        for (int i = 0; i < 10; i++) {
            double a = i * Math.PI / 5.0;
            Vec3 inner = target.add(g.point(a, radius * .42));
            Vec3 outer = target.add(g.point(a, radius * (.84 + .07 * Math.sin(t * 1.2 + i))));
            m.line(inner, outer, i % 2 == 0 ? .70F : .32F);
            Vec3 wingA = outer.add(g.point(a + 2.55, .46));
            Vec3 wingB = outer.add(g.point(a - 2.55, .46));
            m.line(outer, wingA, .28F);
            m.line(outer, wingB, .28F);
        }
        if (life > .82) m.circle(g, target, radius * (1.0 - (life - .82) * .30), 72, .30F);
    }

    /** Locked directional trench and the two real berm lanes generated by MoveEarthService. */
    private static void moveEarth(ArcaneWorldMesh.Builder m, Vec3 direction, Vec3 target,
                                  double range, double t) {
        ArcaneWorldMesh.Basis g = ArcaneWorldMesh.Basis.ground();
        Vec3 forward = flat(direction);
        Vec3 right = new Vec3(-forward.z, 0.0, forward.x);
        double length = SixthCircleSpellService.moveEarthLength(range);
        double trench = SixthCircleSpellService.moveEarthTrenchHalfWidth(range);
        double berm = SixthCircleSpellService.moveEarthBermOffset(range);
        Vec3 a = target.subtract(forward.scale(length * .5));
        Vec3 b = target.add(forward.scale(length * .5));

        // Central excavation boundaries.
        m.line(a.add(right.scale(trench)), b.add(right.scale(trench)), .82F);
        m.line(a.subtract(right.scale(trench)), b.subtract(right.scale(trench)), .82F);
        // Flanking berm centerlines.
        m.line(a.add(right.scale(berm)), b.add(right.scale(berm)), 1.08F);
        m.line(a.subtract(right.scale(berm)), b.subtract(right.scale(berm)), 1.08F);

        for (int i = 0; i <= 10; i++) {
            double q = i / 10.0;
            Vec3 axis = a.add(forward.scale(length * q));
            double pulse = .18 + .10 * (.5 + .5 * Math.sin(t * 5.0 - i * .7));
            m.diamond(g, axis, .16 + pulse, i * .23, .62F, .16F);
            if ((i & 1) == 0) {
                m.line(axis.add(right.scale(trench)), axis.add(right.scale(berm)), .30F);
                m.line(axis.subtract(right.scale(trench)), axis.subtract(right.scale(berm)), .30F);
            }
        }
    }

    /** Six-second fixed corridor; the two side rails are the actual 1.55-block half-width. */
    private static void sunbeam(ArcaneWorldMesh.Builder m, Vec3 direction, Vec3 target,
                                double t, double durationSeconds) {
        ArcaneWorldMesh.Basis f = ArcaneWorldMesh.Basis.facing(safe(direction));
        double half = SixthCircleSpellService.sunbeamHalfWidth();
        Vec3 start = Vec3.ZERO;
        Vec3 end = target;
        Vec3 right = f.right().normalize().scale(half);
        double life = clamp(t / Math.max(.05, durationSeconds), 0.0, 1.0);
        float main = life > .92 ? .54F : 1.12F;
        m.line(start, end, main);
        m.line(start.add(right), end.add(right), .62F);
        m.line(start.subtract(right), end.subtract(right), .62F);
        int ribs = Math.max(4, Math.min(12, (int) Math.ceil(end.length() / 4.0)));
        for (int i = 1; i < ribs; i++) {
            double q = i / (double) ribs;
            Vec3 c = start.add(end.subtract(start).scale(q));
            double shimmer = .72 + .28 * Math.sin(t * 7.0 - i * .9);
            m.line(c.subtract(right.scale(shimmer)), c.add(right.scale(shimmer)), i % 3 == 0 ? .52F : .28F);
        }
    }

    /** Actual 10.5-15.5 m cryogenic denial radius with repeated freeze-front pulses. */
    private static void freezingSphere(ArcaneWorldMesh.Builder m, Vec3 target, double range,
                                       double t, double durationSeconds) {
        ArcaneWorldMesh.Basis g = ArcaneWorldMesh.Basis.ground();
        double radius = SixthCircleSpellService.freezingSphereRadius(range);
        double life = clamp(t / Math.max(.05, durationSeconds), 0.0, 1.0);
        double wave = (t * 1.85) % 1.0;
        m.circle(g, target, radius, 92, life > .94 ? .38F : .82F);
        m.circle(g, target, radius * (.18 + .76 * wave), 70, .52F);
        m.polygon(g, target, radius * .70, 8, Math.PI / 8.0, .38F);
        for (int i = 0; i < 12; i++) {
            double a = i * Math.PI / 6.0;
            Vec3 inner = target.add(g.point(a, radius * .22));
            Vec3 outer = target.add(g.point(a, radius * .92));
            m.line(inner, outer, i % 3 == 0 ? .62F : .26F);
            if ((i & 1) == 0) {
                Vec3 branch = target.add(g.point(a, radius * .63));
                m.line(branch, branch.add(g.point(a + .52, radius * .13)), .24F);
                m.line(branch, branch.add(g.point(a - .52, radius * .13)), .24F);
            }
        }
    }

    private static Vec3 safe(Vec3 value) {
        return value == null || value.lengthSqr() < 1.0E-8 ? new Vec3(0.0, 0.0, 1.0) : value.normalize();
    }

    private static Vec3 flat(Vec3 value) {
        Vec3 flat = value == null ? Vec3.ZERO : new Vec3(value.x, 0.0, value.z);
        return flat.lengthSqr() < 1.0E-8 ? new Vec3(0.0, 0.0, 1.0) : flat.normalize();
    }

    private static double clamp(double value, double min, double max) {
        return Math.max(min, Math.min(max, value));
    }
}
