package kr.moonseungjun.arcanecircle.client;

import kr.moonseungjun.arcanecircle.ArcaneCircle;
import kr.moonseungjun.arcanecircle.magic.SpellCatalog;
import kr.moonseungjun.arcanecircle.magic.SpellDefinition;
import kr.moonseungjun.arcanecircle.magic.SpellMetrics;
import kr.moonseungjun.arcanecircle.network.WorldMagicPayload;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.Identifier;
import net.minecraft.util.context.ContextKey;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.client.event.ExtractLevelRenderStateEvent;
import net.neoforged.neoforge.client.event.SubmitCustomGeometryEvent;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/** Reliable hybrid magic renderer: filled spell bodies, variable-width inscriptions and exact boundaries. */
public final class WorldMagicTracker {
    private static final ContextKey<List<RenderEntry>> DATA_KEY=new ContextKey<>(Identifier.fromNamespaceAndPath(ArcaneCircle.MOD_ID,"world_magic_mesh"));
    private static final Map<UUID,Visual> CHARGES=new HashMap<>();
    private static final List<Visual> RELEASES=new ArrayList<>();
    private static final int MAX_CHARGE=720,MAX_RELEASE=1180,MAX_VISUALS=24,MAX_FRAME=3200;
    private static final double MAX_DISTANCE=192.0*192.0;
    private static final long CHARGE_TTL=2_250_000_000L;
    private static final Set<String> BEAMS=Set.of("ray_of_frost","scorching_ray","lightning_bolt","disintegrate","sunbeam","chain_lightning","prismatic_spray","void_lance","mana_lance","flame_lance","ice_lance");
    private static final Set<String> WAVES=Set.of("thunderwave","gust_of_wind","burning_hands","cone_of_cold","shatter","steam_burst","world_sunder","flame_wave","wind_blade");
    private WorldMagicTracker(){}

    public static void accept(WorldMagicPayload payload){Map<String,String> v=parse(payload.state());String kind=v.getOrDefault("kind","");UUID caster;try{caster=UUID.fromString(v.getOrDefault("caster",""));}catch(Exception e){return;}if("stop".equals(kind)){CHARGES.remove(caster);return;}SpellDefinition spell=SpellCatalog.spell(v.getOrDefault("spell","")).orElse(null);if(spell==null)return;boolean fusion=integer(v,"fusion",0)!=0;int ingredients=Math.max(0,integer(v,"ingredients",0));Vec3 center=new Vec3(decimal(v,"x",0),decimal(v,"y",0),decimal(v,"z",0));Vec3 direction=new Vec3(decimal(v,"dx",0),decimal(v,"dy",0),decimal(v,"dz",1));if(direction.lengthSqr()<1e-8)direction=new Vec3(0,0,1);direction=direction.normalize();double range=Math.max(.1,decimal(v,"range",spell.range())),power=Math.max(.1,decimal(v,"power",Math.max(.1,spell.power())));double progress=clamp(decimal(v,"progress",1),0,1);int duration=Math.max(3,integer(v,"duration",10));long now=System.nanoTime();if("charge".equals(kind)){double visible=Math.max(.10,progress);int step=Math.max(2,Math.min(30,(int)Math.floor(visible*30+.0001)));GeometryKey key=GeometryKey.charge(spell.id(),fusion,ingredients,step,direction,range);Visual old=CHARGES.get(caster);ArcaneWorldMesh mesh=old!=null&&key.equals(old.key)?old.mesh:buildCharge(spell,fusion,ingredients,direction,step/30.0,range);CHARGES.put(caster,new Visual(caster,center,mesh,color(spell),now+CHARGE_TTL,key));return;}if("release".equals(kind)){ArcaneWorldMesh mesh=buildRelease(spell,fusion,ingredients,direction,range,power);while(RELEASES.size()>=MAX_VISUALS)RELEASES.removeFirst();RELEASES.add(new Visual(caster,center,mesh,color(spell),now+duration*50_000_000L,GeometryKey.release(spell.id(),fusion,ingredients,direction,range,power)));CHARGES.remove(caster);}}

    public static void onExtract(ExtractLevelRenderStateEvent event){long now=System.nanoTime();CHARGES.values().removeIf(x->x.expiresAt<now);RELEASES.removeIf(x->x.expiresAt<now);if(CHARGES.isEmpty()&&RELEASES.isEmpty())return;List<RenderEntry> e=new ArrayList<>(CHARGES.size()+RELEASES.size());CHARGES.values().forEach(v->e.add(v.entry()));RELEASES.forEach(v->e.add(v.entry()));event.getRenderState().setRenderData(DATA_KEY,List.copyOf(e));}
    public static void onSubmit(SubmitCustomGeometryEvent event){List<RenderEntry> entries=event.getLevelRenderState().getRenderData(DATA_KEY);if(entries==null||entries.isEmpty())return;Vec3 camera=event.getLevelRenderState().cameraRenderState.pos;float base=Minecraft.getInstance().gameRenderer.gameRenderState().windowRenderState.appropriateLineWidth;float scale=Math.max(.72F,base*.82F);int used=0;for(RenderEntry e:entries){if(used>=MAX_FRAME)break;Vec3 offset=e.center.subtract(camera);if(offset.lengthSqr()>MAX_DISTANCE)continue;event.getPoseStack().pushPose();event.getPoseStack().translate(offset.x,offset.y,offset.z);e.mesh.submit(event.getPoseStack(),event.getSubmitNodeCollector(),e.argb,scale);event.getPoseStack().popPose();used+=e.mesh.size();}}

    private static ArcaneWorldMesh buildCharge(SpellDefinition spell,boolean fusion,int ingredients,Vec3 normal,double progress,double range){ArcaneWorldMesh.Builder m=ArcaneWorldMesh.builder(MAX_CHARGE);ArcaneWorldMesh.Basis b=basis(spell,normal);int c=clampCircle(spell.circle());double scale=clamp(Math.pow(Math.max(.2,range/Math.max(4,spell.range())),.28),.88,1.65);double outer=(.55+c*.12+c*c*.009+(fusion?.22:0))*scale;double rot=Math.floorMod(spell.id().hashCode(),360)*Math.PI/180.0;int rings=c;for(int i=0;i<rings&&!m.full();i++){double local=clamp(progress*c-i,0,1);if(local<=0)continue;double radius=outer*(1-i*.60/Math.max(1,c));double thickness=radius*(i==0?.055:i%2==0?.024:.038)*local;m.band(b,Vec3.ZERO,Math.max(.02,radius-thickness),radius,38+c*5+i*2,1.0F,(float)(.18+.20*local));if(i%2==0)m.arc(b,Vec3.ZERO,radius+thickness*.45,rot+i*.37,Math.PI*(.85+local),18+c*2,1.0F+(i%3)*.55F);}
        if(progress>.12)seal(m,spell,b,outer*.58,rot,clamp((progress-.12)/.48,0,1));
        if(progress>.38){int glyphs=4+c;int visible=Math.max(1,(int)Math.floor(glyphs*clamp((progress-.38)/.45,0,1)));for(int i=0;i<visible&&!m.full();i++){double a=rot+Math.PI*2*i/glyphs;Vec3 center=b.point(a,outer*.79);double s=outer*(.055+(i%3)*.012);if((i&1)==0)m.diamond(b,center,s,rot-a,1.20F,.38F);else m.starPlate(b,center,s,s*.42,3+i%3,rot,1.08F,.28F);m.line(b.point(a,outer*.64),b.point(a+(i%2==0?.04:-.04),outer*.90),.65F+(i%4)*.35F);}}
        if(c>=4&&progress>.55){int layers=Math.min(4,1+(c-3)/2);for(int i=0;i<layers&&!m.full();i++){Vec3 n=b.normal().add(b.right().scale(.18+i*.13)).add(b.up().scale((i%2==0?.22:-.22))).normalize();ArcaneWorldMesh.Basis tilted=ArcaneWorldMesh.Basis.fromNormal(n,b.right());double rr=outer*(1.04+i*.10);m.brokenBand(tilted,Vec3.ZERO,rr-outer*(.018+i*.004),rr,52+c*3,5+i,1.05F,.20F);}}
        if(fusion&&ingredients>=2&&progress>.40){int count=Math.min(3,ingredients);for(int i=0;i<count&&!m.full();i++){double a=rot+Math.PI*2*i/count;Vec3 center=b.point(a,outer*1.34);double r=outer*.18;m.band(b,center,r*.78,r,32,1.15F,.32F);m.starPlate(b,center,r*.65,r*.27,3+i,rot+i,.95F,.26F);m.line(b.point(a,outer*.92),center,1.2F+i*.25F);}m.brokenBand(b,Vec3.ZERO,outer*1.50,outer*1.54,72,7,1.08F,.20F);}
        return m.build();}

    private static void seal(ArcaneWorldMesh.Builder m,SpellDefinition s,ArcaneWorldMesh.Basis b,double r,double rot,double p){if(p<=0)return;int c=clampCircle(s.circle());switch(s.school()){
        case FIRE->{m.starPlate(b,Vec3.ZERO,r,r*(.38+.05*Math.sin(rot)),3+c/3,rot,1.12F,(float)(.12+.20*p));m.star(b,Vec3.ZERO,r,r*.38,3+c/3,rot,1.6F);m.polygonPlate(b,Vec3.ZERO,r*.45,3,-rot,.84F,.16F);}
        case FROST->{int arms=6+(c>=7?2:0);for(int i=0;i<arms*p+.5&&!m.full();i++){double a=rot+Math.PI*2*i/arms;Vec3 root=b.point(a,r*.08),tip=b.point(a,r);m.shard(root.add(tip).scale(.5),tip.subtract(root),b,r*.62,r*.08,1.12F,.34F);m.line(root,tip,i%2==0?1.8F:.8F);}}
        case WIND->{for(int i=0;i<3&&!m.full();i++)m.ribbon(Vec3.ZERO,b.point(rot+i*2.09,.08),b,r*(.85+i*.08),r*(.24-i*.04),2+i,22+c*2,1.0F,.19F);}
        case WARD->{m.polygonPlate(b,Vec3.ZERO,r,6+c/4,rot,.94F,.18F);m.band(b,Vec3.ZERO,r*.72,r*.79,44,1.18F,.27F);m.runeChords(b,Vec3.ZERO,r*.68,6+c,2,-rot,1.2F);}
        case LIFE->{m.disc(b,b.right().scale(r*.20),r*.58,30,.95F,.16F);m.disc(b,b.right().scale(-r*.20),r*.58,30,1.12F,.16F);m.starPlate(b,Vec3.ZERO,r*.36,r*.14,4,rot,1.22F,.28F);}
        case SPACE->{m.brokenBand(b,b.right().scale(r*.12),r*.66,r*.78,42,5,1.12F,.26F);m.brokenBand(b,b.right().scale(-r*.12),r*.50,r*.64,36,4,.76F,.20F);m.runeChords(b,Vec3.ZERO,r*.52,7+c,3,rot,.92F);}
        default->{m.polygonPlate(b,Vec3.ZERO,r,4+c/2,rot,.86F,.16F);m.star(b,Vec3.ZERO,r*.86,r*.32,4+c/3,-rot,1.35F);m.diamond(b,Vec3.ZERO,r*.22,rot,1.22F,.30F);}}
    }

    private static ArcaneWorldMesh buildRelease(SpellDefinition s,boolean fusion,int ingredients,Vec3 dir,double range,double power){ArcaneWorldMesh.Builder m=ArcaneWorldMesh.builder(MAX_RELEASE);ArcaneWorldMesh.Basis b=ArcaneWorldMesh.Basis.facing(dir);int c=clampCircle(s.circle());double pf=clamp(Math.pow(Math.max(.08,power/Math.max(1,s.power())),.18),.82,2.15);float w=.8F+c*.08F;if(BEAMS.contains(s.id()))beam(m,s,dir,b,range,pf,w);else if(WAVES.contains(s.id()))wave(m,s,dir,b,range,pf,w);else switch(s.sigilAnchor()){case FRONT->projectile(m,s,dir,b,range,pf,w);case FEET,GROUND_SELF,GROUND_TARGET->field(m,s,range,pf,w);case BODY->aura(m,s,pf,w);case TARGET->target(m,s,pf,w);}if(fusion){double rr=.55+c*.08;m.brokenBand(b,Vec3.ZERO,rr,rr+.055,54,6,1.15F,.30F);for(int i=0;i<Math.min(3,ingredients);i++)m.shard(b.point(Math.PI*2*i/Math.min(3,ingredients),rr*.72),dir,b,.42+c*.04,.10,1.25F,.42F);}return m.build();}

    private static void beam(ArcaneWorldMesh.Builder m,SpellDefinition s,Vec3 d,ArcaneWorldMesh.Basis b,double range,double pf,float w){double len=Math.min(72,Math.max(4,range)),r=(.045+s.circle()*.012)*pf;switch(s.school()){case FROST->{m.beamPrism(Vec3.ZERO,d,b,len,r*1.8,1.10F,.52F);for(int i=1;i<=5;i++)m.shard(d.scale(len*i/6.0),d,b,r*8,r*2.4,1.18F,.38F);}case FIRE->{m.ribbon(Vec3.ZERO,d,b,len,r*7,3+s.circle()/2,42+s.circle()*4,1.16F,.40F);m.beamPrism(Vec3.ZERO,d,b,len,r,.92F,.34F);}case WIND->{for(int i=-1;i<=1;i++)m.ribbon(b.right().scale(i*r*3),d,b,len,r*5,2+i+2,36,1.0F,.26F);}case SPACE->{m.beamPrism(Vec3.ZERO,d,b,len,r*.85,.85F,.30F);for(int i=1;i<=Math.min(9,3+s.circle());i++){Vec3 p=d.scale(len*i/(Math.min(9,3+s.circle())+1.0));m.brokenBand(b,p,r*3.2,r*4.3,28,4+i%3,1.12F,.30F);}}default->{m.beamPrism(Vec3.ZERO,d,b,len,r*1.35,1.08F,.44F);m.ribbon(Vec3.ZERO,d,b,len,r*4,2+s.circle()/3,38,1.18F,.28F);}}Vec3 end=d.scale(len);m.orb(end,(.22+s.circle()*.07)*pf,22+s.circle()*2,1.18F,.46F);}

    private static void projectile(ArcaneWorldMesh.Builder m,SpellDefinition s,Vec3 d,ArcaneWorldMesh.Basis b,double range,double pf,float w){double len=Math.min(72,Math.max(3.2,range)),core=(.18+s.circle()*.065)*pf;Vec3 end=d.scale(len);switch(s.school()){case FIRE->{m.ribbon(Vec3.ZERO,d,b,len,core*.85,3+s.circle()/2,42+s.circle()*4,1.12F,.34F);for(int i=1;i<=3+s.circle()/2;i++){double t=i/(4.0+s.circle()/2);m.orb(d.scale(len*t),core*(.28+.22*t),14,1.05F,.28F);}m.orb(end,core,24+s.circle()*2,1.25F,.55F);m.starPlate(b,end,core*1.25,core*.52,5,0,1.08F,.32F);}case FROST->{m.shard(end.subtract(d.scale(core*.45)),d,b,core*3.8,core*.58,1.22F,.55F);for(int i=1;i<=4;i++)m.shard(d.scale(len*i/5.0),d,b,core*(1.0+i*.18),core*.20,1.0F,.30F);}case WIND->{for(int i=-1;i<=1;i++)m.ribbon(b.right().scale(i*core*.38),d,b,len,core*(.75+Math.abs(i)*.22),2+i+2,34+s.circle()*3,1.06F,.28F);m.disc(b,end,core*1.25,28,1.10F,.30F);}case SPACE->{m.ribbon(Vec3.ZERO,d,b,len,core*.45,2,32,.80F,.22F);int gates=Math.min(9,3+s.circle());for(int i=1;i<=gates;i++){Vec3 p=d.scale(len*i/(gates+1.0));m.brokenBand(b,p,core*(.62+i*.025),core*(.82+i*.03),30,4+i%4,1.10F,.28F);}m.orb(end,core*.80,22,1.22F,.48F);}case WARD->{m.beamPrism(Vec3.ZERO,d,b,len,core*.30,.90F,.22F);m.polygonPlate(b,end,core*1.35,6+s.circle()/3,0,1.10F,.38F);m.band(b,end,core*.82,core*1.08,36,1.25F,.32F);}case LIFE->{m.ribbon(Vec3.ZERO,d,b,len,core*.65,2,38,1.0F,.25F);m.orb(end,core,26,1.20F,.45F);m.starPlate(b,end,core*.86,core*.34,4,0,1.30F,.36F);}default->{m.beamPrism(Vec3.ZERO,d,b,len,core*.22,.85F,.20F);m.shard(end,d,b,core*3.2,core*.62,1.14F,.48F);m.starPlate(b,end,core*1.18,core*.42,5+s.circle()/3,0,1.10F,.30F);}}}

    private static void wave(ArcaneWorldMesh.Builder m,SpellDefinition s,Vec3 d,ArcaneWorldMesh.Basis b,double range,double pf,float w){double len=Math.min(72,SpellMetrics.waveLength(range)),radius=SpellMetrics.waveEndRadius(s.id(),range,s.circle());m.cone(Vec3.ZERO,d,b,len,radius,7+s.circle(),3+s.circle()/2,w);int slices=Math.min(7,3+s.circle()/2);for(int i=1;i<=slices;i++){double t=i/(double)slices;Vec3 center=d.scale(len*t);double rr=radius*t;m.band(b,center,rr*.86,rr,34+s.circle()*3,1.0F,(float)(.12+.12*t));if(s.school()==SpellDefinition.School.FIRE)for(int j=0;j<Math.min(8,3+s.circle());j++)m.shard(center.add(b.point(Math.PI*2*j/(3+s.circle()),rr*.72)),d,b,rr*.34,rr*.08,1.18F,.30F);else if(s.school()==SpellDefinition.School.FROST)m.starPlate(b,center,rr*.68,rr*.28,6,0,1.12F,.22F);else if(s.school()==SpellDefinition.School.WIND)m.brokenBand(b,center,rr*.62,rr*.78,30,4+i,1.10F,.24F);}}

    private static void field(ArcaneWorldMesh.Builder m,SpellDefinition s,double range,double pf,float w){ArcaneWorldMesh.Basis g=ArcaneWorldMesh.Basis.ground();double radius=Math.min(64,SpellMetrics.effectRadius(s.id(),range,s.circle()));m.disc(g,Vec3.ZERO,radius,64,.72F,.055F);m.band(g,Vec3.ZERO,Math.max(.05,radius-.12-Math.min(.28,radius*.018)),radius,72+s.circle()*4,1.22F,.48F);m.brokenBand(g,Vec3.ZERO,radius*.66,radius*.70,54,5+s.circle()%4,.92F,.22F);seal(m,s,g,radius*.54,Math.floorMod(s.id().hashCode(),360)*Math.PI/180,1);int count=Math.min(12,4+s.circle());for(int i=0;i<count;i++){double a=Math.PI*2*i/count;Vec3 p=g.point(a,radius*.82);if(s.school()==SpellDefinition.School.FROST)m.shard(p,new Vec3(0,1,0),ArcaneWorldMesh.Basis.facing(new Vec3(0,1,0)),.75+s.circle()*.15,.10+s.circle()*.015,1.12F,.34F);else if(s.school()==SpellDefinition.School.FIRE)m.orb(p.add(0,.24,0),.13+s.circle()*.025,14,1.18F,.34F);else m.diamond(g,p,.12+s.circle()*.018,a,1.10F,.30F);}}
    private static void aura(ArcaneWorldMesh.Builder m,SpellDefinition s,double pf,float w){double r=(1.0+s.circle()*.20)*pf;ArcaneWorldMesh.Basis g=ArcaneWorldMesh.Basis.ground();m.orb(new Vec3(0,-.72,0),r,28,1.0F,.22F);m.band(g,new Vec3(0,-.92,0),r*.88,r,54,1.18F,.32F);for(int i=0;i<3+s.circle()/2;i++){double y=-.70+i*(1.6/(2+s.circle()/2));m.brokenBand(g,new Vec3(0,y,0),r*(.55+i*.06),r*(.60+i*.06),40,5+i,1.08F,.24F);}}
    private static void target(ArcaneWorldMesh.Builder m,SpellDefinition s,double pf,float w){ArcaneWorldMesh.Basis g=ArcaneWorldMesh.Basis.ground();double r=(.68+s.circle()*.16)*pf;int layers=3+s.circle()/2;for(int i=0;i<layers;i++){double t=i/(double)Math.max(1,layers-1),y=-.9+t*(2.2+s.circle()*.10);m.brokenBand(g,new Vec3(0,y,0),r*(.82+.08*Math.sin(Math.PI*t)),r*(.96+.08*Math.sin(Math.PI*t)),42,4+i,1.08F,.28F);}m.orb(new Vec3(0,.25,0),r*.62,22,1.18F,.30F);}

    private static ArcaneWorldMesh.Basis basis(SpellDefinition s,Vec3 n){return switch(s.sigilAnchor()){case FEET,GROUND_SELF,GROUND_TARGET->ArcaneWorldMesh.Basis.ground();default->ArcaneWorldMesh.Basis.facing(n);};}
    private static int color(SpellDefinition s){return switch(s.school()){case FIRE->0xEFFF633D;case FROST->0xEF69E4FF;case WIND->0xE873E8C2;case WARD->0xEFC89AFF;case LIFE->0xEF74E894;case SPACE->0xEFA778FF;default->0xEF829FFF;};}
    private static int clampCircle(int c){return Math.max(1,Math.min(9,c));}
    private static Map<String,String> parse(String state){Map<String,String> m=new HashMap<>();for(String p:state.split(";")){int i=p.indexOf('=');if(i>0)m.put(p.substring(0,i),p.substring(i+1));}return m;}
    private static int integer(Map<String,String> v,String k,int f){try{return Integer.parseInt(v.getOrDefault(k,Integer.toString(f)));}catch(Exception e){return f;}}
    private static double decimal(Map<String,String> v,String k,double f){try{return Double.parseDouble(v.getOrDefault(k,Double.toString(f)));}catch(Exception e){return f;}}
    private static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}
    private record Visual(UUID caster,Vec3 center,ArcaneWorldMesh mesh,int argb,long expiresAt,GeometryKey key){RenderEntry entry(){return new RenderEntry(center,mesh,argb);}}
    private record RenderEntry(Vec3 center,ArcaneWorldMesh mesh,int argb){}
    private record GeometryKey(String id,boolean fusion,int ingredients,int progress,int dx,int dy,int dz,int range,int power,boolean release){static GeometryKey charge(String id,boolean f,int n,int p,Vec3 d,double r){return new GeometryKey(id,f,n,p,q(d.x,32),q(d.y,32),q(d.z,32),q(r,6),0,false);}static GeometryKey release(String id,boolean f,int n,Vec3 d,double r,double p){return new GeometryKey(id,f,n,30,q(d.x,32),q(d.y,32),q(d.z,32),q(r,6),q(p,3),true);}private static int q(double v,int s){return(int)Math.round(v*s);}}
}
