org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.19
fabric_api_version=0.160.0+26.2

mod_id=earth_to_stars
mod_name=EARTH TO STARS
mod_version=0.3.0-alpha.1
maven_group=kr.moonseungjun.earthtostars
archives_base_name=earth_to_stars
