org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=1.20.1-47.4.0

valkyrien_skies_version=2.4.10
genesis_version=1.20.1-0.7.3
zps_version=1.20.1-2.4.0
zpl_version=1.20.1-1.5.0

mod_id=earth_to_stars
mod_name=EARTH TO STARS
mod_license=All Rights Reserved
mod_version=0.2.0-alpha.1
mod_group_id=kr.moonseungjun.earthtostars
