#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAVA = ROOT / 'src/main/java/kr/moonseungjun/frontiersettlement'

def text(path): return path.read_text(encoding='utf-8')
def write(path, content): path.write_text(content, encoding='utf-8')
def repl(path, old, new):
    src=text(path)
    if old not in src: raise SystemExit(f'missing anchor in {path}: {old[:160]!r}')
    write(path, src.replace(old,new,1))

service = JAVA/'settlement/SettlementOutpostService.java'
repl(service,
'''    public record StartResult(boolean started, String message) {}\n    public record PlacementCheck(boolean valid, int roadIndex, BlockPos gate,''',
'''    public record StartResult(boolean started, String message) {}\n    private record BlockSnapshot(BlockPos pos, BlockState state) {}\n    public record PlacementCheck(boolean valid, int roadIndex, BlockPos gate,''')

repl(service,
'''        applyGradeCell(level, target);\n        builder.swing(InteractionHand.MAIN_HAND);\n        data.advanceOutpostConstruction();''',
'''        if (!applyGradeCell(level, target)) return false;\n        builder.swing(InteractionHand.MAIN_HAND);\n        data.advanceOutpostConstruction();''')

old='''    private static void applyGradeCell(ServerLevel level, BlockPos target) {\n        for (int y = target.getY() + OutpostBlueprints.CLEAR_HEIGHT; y >= target.getY() + 1; y--) {\n            BlockPos pos = new BlockPos(target.getX(), y, target.getZ());\n            if (!level.getBlockState(pos).isAir()) {\n                level.setBlock(pos, Blocks.AIR.defaultBlockState(), DIRECT_BLOCK_UPDATE);\n            }\n        }\n\n        BlockPos cursor = target.below();\n        for (int depth = 0; depth <= MAX_FILL_DEPTH; depth++) {\n            BlockState current = level.getBlockState(cursor);\n            if (!current.isAir() && !current.canBeReplaced()) break;\n            level.setBlock(cursor, Blocks.COARSE_DIRT.defaultBlockState(), DIRECT_BLOCK_UPDATE);\n            cursor = cursor.below();\n        }\n\n        BlockState current = level.getBlockState(target);\n        if (current.isAir() || current.canBeReplaced()) {\n            level.setBlock(target, Blocks.COARSE_DIRT.defaultBlockState(), DIRECT_BLOCK_UPDATE);\n        }\n    }\n'''
new='''    /** Apply one outpost grade cell as one reversible world transaction. */\n    private static boolean applyGradeCell(ServerLevel level, BlockPos target) {\n        List<BlockSnapshot> changed = new ArrayList<>();\n        for (int y = target.getY() + OutpostBlueprints.CLEAR_HEIGHT; y >= target.getY() + 1; y--) {\n            BlockPos pos = new BlockPos(target.getX(), y, target.getZ());\n            if (!level.hasChunkAt(pos)) { rollbackGradeMutation(level, changed); return false; }\n            if (!level.getBlockState(pos).isAir()\n                    && !setGradeBlock(level, pos, Blocks.AIR.defaultBlockState(), changed)) {\n                rollbackGradeMutation(level, changed);\n                return false;\n            }\n        }\n\n        BlockPos cursor = target.below();\n        for (int depth = 0; depth <= MAX_FILL_DEPTH; depth++) {\n            if (!level.hasChunkAt(cursor)) { rollbackGradeMutation(level, changed); return false; }\n            BlockState current = level.getBlockState(cursor);\n            if (!current.isAir() && !current.canBeReplaced()) break;\n            if (!setGradeBlock(level, cursor, Blocks.COARSE_DIRT.defaultBlockState(), changed)) {\n                rollbackGradeMutation(level, changed);\n                return false;\n            }\n            cursor = cursor.below();\n        }\n\n        if (!level.hasChunkAt(target)) { rollbackGradeMutation(level, changed); return false; }\n        BlockState current = level.getBlockState(target);\n        if ((current.isAir() || current.canBeReplaced())\n                && !setGradeBlock(level, target, Blocks.COARSE_DIRT.defaultBlockState(), changed)) {\n            rollbackGradeMutation(level, changed);\n            return false;\n        }\n        return true;\n    }\n\n    private static boolean setGradeBlock(ServerLevel level, BlockPos pos, BlockState next,\n                                         List<BlockSnapshot> changed) {\n        BlockState current = level.getBlockState(pos);\n        if (current.equals(next)) return true;\n        if (!level.setBlock(pos, next, DIRECT_BLOCK_UPDATE)) return false;\n        changed.add(new BlockSnapshot(pos, current));\n        return true;\n    }\n\n    private static void rollbackGradeMutation(ServerLevel level, List<BlockSnapshot> changed) {\n        for (int i = changed.size() - 1; i >= 0; i--) {\n            BlockSnapshot snapshot = changed.get(i);\n            if (level.hasChunkAt(snapshot.pos())) {\n                level.setBlock(snapshot.pos(), snapshot.state(), DIRECT_BLOCK_UPDATE);\n            }\n        }\n    }\n'''
repl(service,old,new)

props=ROOT/'gradle.properties'
repl(props,'mod_version=0.1.0-alpha.60','mod_version=0.1.0-alpha.61')
repl(props,'plus rollback-safe ordinary building and terrain material transactions.','plus rollback-safe ordinary building and terrain material transactions, and rollback-safe outpost grading cells.')

lock=ROOT/'COMPANION_LOCK.json'
repl(lock,'"frontier_settlement": "0.1.0-alpha.60"','"frontier_settlement": "0.1.0-alpha.61"')
repl(lock,
'''    "Alpha.60 makes ordinary building placement and Alpha.44 terrain grading transaction-safe: required crate material is verified before mutation, successful world placement precedes ItemStack consumption/state advance, failed placement consumes nothing, and unexpected post-placement consumption failure rolls the newly changed blocks back. Existing already-paid final repair semantics are retained to avoid double charging.",''',
'''    "Alpha.60 makes ordinary building placement and Alpha.44 terrain grading transaction-safe: required crate material is verified before mutation, successful world placement precedes ItemStack consumption/state advance, failed placement consumes nothing, and unexpected post-placement consumption failure rolls the newly changed blocks back. Existing already-paid final repair semantics are retained to avoid double charging.",\n    "Alpha.61 makes outpost grading rollback-safe: each loaded grade cell snapshots every changed BlockState, checks every setBlock result, restores successful partial mutations in reverse order on failure, and advances the persisted outpost step only after the complete grade cell succeeds. No new save field, resource, worker, key or companion dependency is added.",''')
repl(lock,'so Alpha.60 keeps only HUD collision avoidance','so Alpha.61 keeps only HUD collision avoidance')

readme=ROOT/'README.md'
repl(readme,'## Current version: 0.1.0-alpha.60','## Current version: 0.1.0-alpha.61')
repl(readme,'No new Alpha.60 key was added.','No new Alpha.61 key was added.')
repl(readme,'Alpha.40–60 deepen existing systems rather than inventing meaningless 16th–20th buildings.','Alpha.40–61 deepen existing systems rather than inventing meaningless 16th–20th buildings.')
alpha61='''## Alpha.61 — rollback-safe outpost grading\n\nAlpha.61 closes the remaining old-style terrain mutation in physical outpost construction before save/reload acceptance.\n\n- outpost grading keeps the existing bounded 9×9 footprint and `MAX_FILL_DEPTH=2`; no larger terrain envelope is introduced;\n- one grade cell snapshots every world block it actually changes;\n- every clear/fill/final-grade `setBlock` result is checked;\n- if any placement fails or a required cell becomes unloaded, every earlier successful mutation in that grade cell is restored in reverse order;\n- `advanceOutpostConstruction()` runs only after the complete grade cell succeeds;\n- no resource is minted or consumed by grading, so rollback never creates a refund currency or loose block drops;\n- physical outpost blueprint construction remains the Alpha.55 `setBlock -> carried ItemStack consume -> step advance` authority;\n- no new save field, worker, key, UI, building family, force-load, teleport, `destroyBlock` or `dropResources` path is added.\n\nThis is long-play/save hardening, not a claim that two-player runtime acceptance is finished.\n\n'''
repl(readme,'## Alpha.60 — rollback-safe ordinary construction transactions\n',alpha61+'## Alpha.60 — rollback-safe ordinary construction transactions\n')

can=ROOT/'CANONICAL_PLAN.md'
repl(can,'Current canonical implementation: **0.1.0-alpha.60**.','Current canonical implementation: **0.1.0-alpha.61**.')
repl(can,'The original target was roughly 15–20 meaningful families. Alpha.40–60 deepen systems rather than adding fake families.','The original target was roughly 15–20 meaningful families. Alpha.40–61 deepen systems rather than adding fake families.')
alpha61can='''### Alpha.61 outpost grade-cell transaction hardening\n\n- the existing outpost grading envelope and save phase remain unchanged;\n- each grade cell snapshots all changed BlockStates;\n- every clear/support/final-grade `setBlock` must succeed;\n- an unloaded required cell or failed placement rolls back successful partial changes in reverse order;\n- persisted outpost construction step advances only after the full grade cell succeeds;\n- grading still creates no loose drops, virtual soil, resource refund or second construction authority;\n- no save schema/key/building/worker/companion change.\n\n'''
repl(can,'### Alpha.60 ordinary construction transaction hardening\n',alpha61can+'### Alpha.60 ordinary construction transaction hardening\n')
repl(can,'## 14. Current playable slice after Alpha.60','## 14. Current playable slice after Alpha.61')
repl(can,'- Alpha.60 rollback-safe ordinary building placement + Alpha.44 grade-cell physical material transactions;','- Alpha.60 rollback-safe ordinary building placement + Alpha.44 grade-cell physical material transactions;\n- Alpha.61 rollback-safe outpost grade-cell terrain mutation before persisted step advance;')
repl(can,'## 15. Unfinished original-scope priorities after Alpha.60','## 15. Unfinished original-scope priorities after Alpha.61')
repl(can,'18. Alpha.60 building setBlock failure/rollback + terrain retaining rollback/pre-fill-cost acceptance;\n19. full companion lock fresh-world client/server runtime;',
'''18. Alpha.60 building setBlock failure/rollback + terrain retaining rollback/pre-fill-cost acceptance;\n19. Alpha.61 outpost grade-cell failure/rollback + unload/save-reload acceptance;\n20. full companion lock fresh-world client/server runtime;''')
repl(can,'20. true Xaero markers only if a stable supported API appears;\n21. moving boat/waterborne merchant only if presentation value justifies it and it never becomes a second logistics authority.',
'''21. true Xaero markers only if a stable supported API appears;\n22. moving boat/waterborne merchant only if presentation value justifies it and it never becomes a second logistics authority.''')
repl(can,'- road stairs/short bridge and outpost route movement;','- road stairs/short bridge and outpost route movement, including Alpha.61 rollback-safe outpost grading;')

gap=ROOT/'COMPLETION_GAP_AUDIT.md'
repl(gap,'현재 구현 기준: `0.1.0-alpha.60`','현재 구현 기준: `0.1.0-alpha.61`')
repl(gap,'| 전초기지 물리 시공 | 완료 | persisted |','| 전초기지 물리 시공 | 완료 | persisted |\n| 전초기지 grading 원자성 | **완료/부분** | Alpha.61 grade-cell snapshot/rollback; 실제 실패주입·save/reload acceptance 남음 |')
alpha61gap='''### Alpha.61 전초 grading transaction 감사\n\n- 기존 9×9 전초 footprint/최대 성토2/save phase 유지;\n- 한 grade cell에서 실제 변경 전 BlockState를 모두 snapshot;\n- clear/support/final grade `setBlock` 성공을 전부 확인;\n- 필요한 cell unload 또는 배치 실패 시 이미 성공한 변경을 역순 rollback;\n- complete grade cell 성공 뒤에만 persisted outpost step advance;\n- grading loose drop/virtual soil/refund/resource consume 없음;\n- 새 save field/worker/key/building/force-load/teleport 없음.\n\n실제 실패주입, 청크 경계 unload, save/reload acceptance는 아직 남는다.\n\n'''
repl(gap,'### Alpha.60 일반 건설 transaction 감사\n',alpha61gap+'### Alpha.60 일반 건설 transaction 감사\n')
repl(gap,'17. Alpha.60 building placement failure/rollback + grade retaining consume rollback/pre-fill-cost acceptance;\n18. full companion lock fresh-world client/server runtime;',
'''17. Alpha.60 building placement failure/rollback + grade retaining consume rollback/pre-fill-cost acceptance;\n18. Alpha.61 outpost grade-cell failure/rollback + unload/save-reload acceptance;\n19. full companion lock fresh-world client/server runtime;''')
repl(gap,'19. true Xaero marker는 stable supported API가 생길 때만;\n20. moving boat/waterborne merchant는 두 번째 logistics authority가 되지 않는 경우에만 선택적 presentation.',
'''20. true Xaero marker는 stable supported API가 생길 때만;\n21. moving boat/waterborne merchant는 두 번째 logistics authority가 되지 않는 경우에만 선택적 presentation.''')

# Alpha.61 source audit.
a61=ROOT/'tools/test_alpha61_source.py'
write(a61,"""#!/usr/bin/env python3\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]; JAVA=ROOT/'src/main/java/kr/moonseungjun/frontiersettlement'; A60=ROOT/'tools/test_alpha60_source.py'\ndef text(p): return p.read_text(encoding='utf-8')\ndef must(s,tokens,label):\n    for t in tokens:\n        if t not in s: raise SystemExit(f'{label} missing: {t}')\ndef forbid(s,tokens,label):\n    for t in tokens:\n        if t in s: raise SystemExit(f'{label}: {t}')\na=text(A60).replace(\"print('Frontier Settlement alpha.23-60 cumulative source audit: PASS')\",'pass').replace('0.1.0-alpha.60','0.1.0-alpha.61'); ns={'__file__':str(A60),'__name__':'__main__'}; exec(compile(a,str(A60),'exec'),ns,ns)\noutpost=text(JAVA/'settlement/SettlementOutpostService.java'); props=text(ROOT/'gradle.properties'); lock=text(ROOT/'COMPANION_LOCK.json'); building=text(JAVA/'settlement/BuildingType.java')\nmust(outpost,('private record BlockSnapshot(BlockPos pos, BlockState state)','if (!applyGradeCell(level, target)) return false;','private static boolean applyGradeCell(ServerLevel level, BlockPos target)','List<BlockSnapshot> changed = new ArrayList<>()','private static boolean setGradeBlock','if (!level.setBlock(pos, next, DIRECT_BLOCK_UPDATE)) return false;','private static void rollbackGradeMutation','for (int i = changed.size() - 1; i >= 0; i--)','if (level.hasChunkAt(snapshot.pos()))'),'alpha.61 outpost grade transaction')\napply=outpost.find('if (!applyGradeCell(level, target)) return false;'); advance=outpost.find('data.advanceOutpostConstruction();',apply)\nif min(apply,advance)<0 or not apply < advance: raise SystemExit('alpha.61 outpost grade must succeed before step advance')\nforbid(outpost,('destroyBlock(','dropResources(','forceChunk','setChunkForced','teleportTo('),'alpha.61 outpost grading keeps no-drop/no-force-load authority')\nenum_block=building.split('public enum BuildingType {',1)[1].split(';',1)[0]; actual=[line.strip().split('(',1)[0] for line in enum_block.splitlines() if '(' in line]; expected=['HOUSE','LUMBER_CAMP','FARM','QUARRY','MINE','WAREHOUSE','CONSTRUCTION_OFFICE','BLACKSMITH','WORKSHOP','ADVANCED_WORKSHOP','GUARD_POST','WATCHTOWER','BARRACKS','MARKET','CART_STATION']\nif actual!=expected: raise SystemExit(f'alpha.61 expected exact 15 functional building families, got: {actual}')\nmust(props,('mod_version=0.1.0-alpha.61','rollback-safe outpost grading cells'),'alpha.61 props')\nmust(lock,('\\\"frontier_settlement\\\": \\\"0.1.0-alpha.61\\\"','Alpha.61 makes outpost grading rollback-safe','advances the persisted outpost step only after the complete grade cell succeeds','\\\"status\\\": \\\"candidate_runtime_lock\\\"'),'alpha.61 lock')\nprint('Frontier Settlement alpha.23-61 cumulative source audit: PASS')\n""")

write(ROOT/'tools/test_alpha61_docs.py',"""#!/usr/bin/env python3\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]\ndef text(n): return (ROOT/n).read_text(encoding='utf-8')\ndef must(s,tokens,label):\n    for t in tokens:\n        if t not in s: raise SystemExit(f'{label} missing: {t}')\nreadme=text('README.md'); can=text('CANONICAL_PLAN.md'); gap=text('COMPLETION_GAP_AUDIT.md')\nmust(readme,('## Current version: 0.1.0-alpha.61','## Alpha.61 — rollback-safe outpost grading','snapshots every world block','restored in reverse order','advanceOutpostConstruction()` runs only after the complete grade cell succeeds','two-player runtime acceptance'),'alpha.61 README')\nmust(can,('Current canonical implementation: **0.1.0-alpha.61**','### Alpha.61 outpost grade-cell transaction hardening','rolls back successful partial changes in reverse order','persisted outpost construction step advances only after the full grade cell succeeds','## 14. Current playable slice after Alpha.61','## 15. Unfinished original-scope priorities after Alpha.61'),'alpha.61 canonical')\nmust(gap,('현재 구현 기준: `0.1.0-alpha.61`','전초기지 grading 원자성 | **완료/부분**','### Alpha.61 전초 grading transaction 감사','역순 rollback','실제 실패주입, 청크 경계 unload, save/reload acceptance는 아직 남는다'),'alpha.61 gap')\nprint('Frontier Settlement alpha.61 canonical docs audit: PASS')\n""")
print('Applied Frontier Settlement 0.1.0-alpha.61 rollback-safe outpost grading.')
