org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.38-beta

mod_id=senbonzakura
mod_name=Senbonzakura Showcase
mod_license=All Rights Reserved
mod_version=0.1.0-alpha.13
mod_group_id=kr.moonseungjun.senbonzakura
