org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.62

mod_id=turnbound
mod_name=TURNBOUND
mod_license=All Rights Reserved
mod_version=0.1.0-alpha.11
mod_group_id=io.github.q93503128.turnbound
uilib_version_id=7PnHRvVW
geckolib_version_id=Kgc42zo3
