org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.38-beta

mod_id=survivalascension
mod_name=Survival Ascension
mod_license=All Rights Reserved
mod_version=0.22.0-alpha.1
mod_group_id=kr.moonseungjun.survivalascension
