org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.40-beta
iris_version_range=[1.11.2,)
sodium_version_range=[0.9.1,)
mod_id=shaderlab
mod_name=Shader Lab Reverie
mod_license=GPL-3.0-or-later
mod_version=0.7.0-alpha.8
mod_group_id=kr.moonseungjun.shaderlab
mod_authors=문승준
mod_description=Noble의 현실적 물·하늘·빛과 SPBR LabPBR 재질을 결합하고 식물 알파 오류, 과도한 렌더링 비용, 보이지 않던 안개를 수정한 몽환적 Minecraft Java 26.2 클라이언트 쉐이더 모드.
noble_project=noble
noble_version_id=3cIADbit
shader_pack_name=ShaderLab-Reverie-0.7.zip
iris_modrinth_version_id=bXt6zsZT
sodium_modrinth_version_id=KHPycol7
