org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.40-beta
iris_version_range=[1.11.2,)
sodium_version_range=[0.9.1,)
mod_id=shaderlab
mod_name=Shader Lab Dreamscape
mod_license=All Rights Reserved
mod_version=0.4.0-alpha.4
mod_group_id=kr.moonseungjun.shaderlab
mod_authors=문승준
mod_description=공식 MIT Sarp Shaders를 자동 설치하고 Iris에서 선택하는 Minecraft Java 26.2용 비공개 고품질 쉐이더 테스트 부트스트랩.
sarp_project=sarp
sarp_version_id=AwTfcPdR
shader_pack_name=ShaderLab-Dreamscape-0.4.zip
