modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="earth_to_stars"
version="${version}"
displayName="EARTH TO STARS"
authors="MoonSeungJun"
description='''
Earth-to-space progression built on Valkyrien Skies block-ship physics and Genesis orbital space.
'''

[[dependencies.earth_to_stars]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="valkyrienskies"
mandatory=true
versionRange="[2.4.10,2.5.0)"
ordering="NONE"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="genesis"
mandatory=true
versionRange="[1.20.1-0.7.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="vlib"
mandatory=true
versionRange="[1.20.1-0.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="zps"
mandatory=true
versionRange="[1.20.1-2.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.earth_to_stars]]
modId="zpl"
mandatory=true
versionRange="[1.20.1-1.5.0,)"
ordering="AFTER"
side="BOTH"
